(cl:in-package lift_action-msg)
(cl:export '(LIFTERFAULT-VAL
          LIFTERFAULT
          EXTRACTORFAULT-VAL
          EXTRACTORFAULT
          TURNTABLEFAULT-VAL
          TURNTABLEFAULT
          SWINGARMFAULT-VAL
          SWINGARMFAULT
          EMERGENCYPBFAULT-VAL
          EMERGENCYPBFAULT
          SWINGARMSENSORZEROFAULT-VAL
          SWINGARMSENSORZEROFAULT
          SWINGARMSENSORNINETYFAULT-VAL
          SWINGARMSENSORNINETYFAULT
          TURNTABLESENSORZEROFAULT-VAL
          TURNTABLESENSORZEROFAULT
          EXTRACTORSENSORLASERFAULT-VAL
          EXTRACTORSENSORLASERFAULT
))