# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from anscer_msgs/ChargeGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import anscer_msgs.msg

class ChargeGoal(genpy.Message):
  _md5sum = "1e9af38045a149080a90c0719ad06ab1"
  _type = "anscer_msgs/ChargeGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
anscer_msgs/ChargeInfo charge_info

================================================================================
MSG: anscer_msgs/ChargeInfo
uint8 CONNECTED=1
uint8 DISCONNECTED=2
uint8 OVERRIDE=3

bool charger_activate
int32 charge_time
bool ignore_time
float32 charge_percentage
bool ignore_percentage
"""
  __slots__ = ['charge_info']
  _slot_types = ['anscer_msgs/ChargeInfo']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       charge_info

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ChargeGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.charge_info is None:
        self.charge_info = anscer_msgs.msg.ChargeInfo()
    else:
      self.charge_info = anscer_msgs.msg.ChargeInfo()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BiBfB().pack(_x.charge_info.charger_activate, _x.charge_info.charge_time, _x.charge_info.ignore_time, _x.charge_info.charge_percentage, _x.charge_info.ignore_percentage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.charge_info is None:
        self.charge_info = anscer_msgs.msg.ChargeInfo()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.charge_info.charger_activate, _x.charge_info.charge_time, _x.charge_info.ignore_time, _x.charge_info.charge_percentage, _x.charge_info.ignore_percentage,) = _get_struct_BiBfB().unpack(str[start:end])
      self.charge_info.charger_activate = bool(self.charge_info.charger_activate)
      self.charge_info.ignore_time = bool(self.charge_info.ignore_time)
      self.charge_info.ignore_percentage = bool(self.charge_info.ignore_percentage)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BiBfB().pack(_x.charge_info.charger_activate, _x.charge_info.charge_time, _x.charge_info.ignore_time, _x.charge_info.charge_percentage, _x.charge_info.ignore_percentage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.charge_info is None:
        self.charge_info = anscer_msgs.msg.ChargeInfo()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.charge_info.charger_activate, _x.charge_info.charge_time, _x.charge_info.ignore_time, _x.charge_info.charge_percentage, _x.charge_info.ignore_percentage,) = _get_struct_BiBfB().unpack(str[start:end])
      self.charge_info.charger_activate = bool(self.charge_info.charger_activate)
      self.charge_info.ignore_time = bool(self.charge_info.ignore_time)
      self.charge_info.ignore_percentage = bool(self.charge_info.ignore_percentage)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BiBfB = None
def _get_struct_BiBfB():
    global _struct_BiBfB
    if _struct_BiBfB is None:
        _struct_BiBfB = struct.Struct("<BiBfB")
    return _struct_BiBfB
