# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from anscer_msgs/ChargeInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ChargeInfo(genpy.Message):
  _md5sum = "07a5813f322d0f1699de1925e6361210"
  _type = "anscer_msgs/ChargeInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 CONNECTED=1
uint8 DISCONNECTED=2
uint8 OVERRIDE=3

bool charger_activate
int32 charge_time
bool ignore_time
float32 charge_percentage
bool ignore_percentage
"""
  # Pseudo-constants
  CONNECTED = 1
  DISCONNECTED = 2
  OVERRIDE = 3

  __slots__ = ['charger_activate','charge_time','ignore_time','charge_percentage','ignore_percentage']
  _slot_types = ['bool','int32','bool','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       charger_activate,charge_time,ignore_time,charge_percentage,ignore_percentage

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ChargeInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.charger_activate is None:
        self.charger_activate = False
      if self.charge_time is None:
        self.charge_time = 0
      if self.ignore_time is None:
        self.ignore_time = False
      if self.charge_percentage is None:
        self.charge_percentage = 0.
      if self.ignore_percentage is None:
        self.ignore_percentage = False
    else:
      self.charger_activate = False
      self.charge_time = 0
      self.ignore_time = False
      self.charge_percentage = 0.
      self.ignore_percentage = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_BiBfB().pack(_x.charger_activate, _x.charge_time, _x.ignore_time, _x.charge_percentage, _x.ignore_percentage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.charger_activate, _x.charge_time, _x.ignore_time, _x.charge_percentage, _x.ignore_percentage,) = _get_struct_BiBfB().unpack(str[start:end])
      self.charger_activate = bool(self.charger_activate)
      self.ignore_time = bool(self.ignore_time)
      self.ignore_percentage = bool(self.ignore_percentage)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_BiBfB().pack(_x.charger_activate, _x.charge_time, _x.ignore_time, _x.charge_percentage, _x.ignore_percentage))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.charger_activate, _x.charge_time, _x.ignore_time, _x.charge_percentage, _x.ignore_percentage,) = _get_struct_BiBfB().unpack(str[start:end])
      self.charger_activate = bool(self.charger_activate)
      self.ignore_time = bool(self.ignore_time)
      self.ignore_percentage = bool(self.ignore_percentage)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BiBfB = None
def _get_struct_BiBfB():
    global _struct_BiBfB
    if _struct_BiBfB is None:
        _struct_BiBfB = struct.Struct("<BiBfB")
    return _struct_BiBfB
