# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from anscer_msgs/ZoneInformation.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import anscer_msgs.msg

class ZoneInformation(genpy.Message):
  _md5sum = "37c3f4225b2755242cf0813eaae1cb1a"
  _type = "anscer_msgs/ZoneInformation"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """anscer_msgs/Indication indication_info
float32 speed_factor

================================================================================
MSG: anscer_msgs/Indication
string color
int8 color_mode
bool buzzer
int8 buzzer_mode
int16 priority


"""
  __slots__ = ['indication_info','speed_factor']
  _slot_types = ['anscer_msgs/Indication','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       indication_info,speed_factor

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ZoneInformation, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.indication_info is None:
        self.indication_info = anscer_msgs.msg.Indication()
      if self.speed_factor is None:
        self.speed_factor = 0.
    else:
      self.indication_info = anscer_msgs.msg.Indication()
      self.speed_factor = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.indication_info.color
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_bBbhf().pack(_x.indication_info.color_mode, _x.indication_info.buzzer, _x.indication_info.buzzer_mode, _x.indication_info.priority, _x.speed_factor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.indication_info is None:
        self.indication_info = anscer_msgs.msg.Indication()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.indication_info.color = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.indication_info.color = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.indication_info.color_mode, _x.indication_info.buzzer, _x.indication_info.buzzer_mode, _x.indication_info.priority, _x.speed_factor,) = _get_struct_bBbhf().unpack(str[start:end])
      self.indication_info.buzzer = bool(self.indication_info.buzzer)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.indication_info.color
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_bBbhf().pack(_x.indication_info.color_mode, _x.indication_info.buzzer, _x.indication_info.buzzer_mode, _x.indication_info.priority, _x.speed_factor))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.indication_info is None:
        self.indication_info = anscer_msgs.msg.Indication()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.indication_info.color = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.indication_info.color = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.indication_info.color_mode, _x.indication_info.buzzer, _x.indication_info.buzzer_mode, _x.indication_info.priority, _x.speed_factor,) = _get_struct_bBbhf().unpack(str[start:end])
      self.indication_info.buzzer = bool(self.indication_info.buzzer)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_bBbhf = None
def _get_struct_bBbhf():
    global _struct_bBbhf
    if _struct_bBbhf is None:
        _struct_bBbhf = struct.Struct("<bBbhf")
    return _struct_bBbhf
