map_xspacing: 0.5
map_yspacing: 0.5
tagmap: 
  { 
   points: 
   [ 
      {tag_id: 1,  row: 8, col: 10 },
      {tag_id: 2,  row: 9, col: 10 },
      {tag_id: 3,  row: 10, col: 10 },
      {tag_id: 4,  row: 11, col: 10 },
      {tag_id: 5,  row: 12, col: 10 },
      {tag_id: 6,  row: 13, col: 10 },
      {tag_id: 7,  row: 14, col: 10 },
      {tag_id: 8,  row: 15, col: 10 },
      {tag_id: 9,  row: 15, col: 30 },
      {tag_id: 10,  row: 15, col: 37 },
      {tag_id: 11,  row: 15, col: 42 },
      {tag_id: 12,  row: 15, col: 47 },
      {tag_id: 13,  row: 16, col: 10 },
      {tag_id: 14,  row: 16, col: 30 },
      {tag_id: 15,  row: 16, col: 37 },
      {tag_id: 16,  row: 16, col: 42 },
      {tag_id: 17,  row: 16, col: 47 },
      {tag_id: 18,  row: 17, col: 10 },
      {tag_id: 19,  row: 17, col: 30 },
      {tag_id: 20,  row: 17, col: 37 },
      {tag_id: 21,  row: 17, col: 42 },
      {tag_id: 22,  row: 17, col: 47 },
      {tag_id: 23,  row: 18, col: 10 },
      {tag_id: 24,  row: 18, col: 30 },
      {tag_id: 25,  row: 18, col: 37 },
      {tag_id: 26,  row: 18, col: 42 },
      {tag_id: 27,  row: 18, col: 47 },
      {tag_id: 28,  row: 19, col: 10 },
      {tag_id: 29,  row: 19, col: 30 },
      {tag_id: 30,  row: 19, col: 37 },
      {tag_id: 31,  row: 19, col: 42 },
      {tag_id: 32,  row: 19, col: 47 },
      {tag_id: 33,  row: 20, col: 10 },
      {tag_id: 34,  row: 20, col: 30 },
      {tag_id: 35,  row: 20, col: 37 },
      {tag_id: 36,  row: 20, col: 42 },
      {tag_id: 37,  row: 20, col: 47 },
      {tag_id: 38,  row: 21, col: 10 },
      {tag_id: 39,  row: 21, col: 30 },
      {tag_id: 40,  row: 21, col: 37 },
      {tag_id: 41,  row: 21, col: 42 },
      {tag_id: 42,  row: 21, col: 47 },
      {tag_id: 43,  row: 22, col: 10 },
      {tag_id: 44,  row: 22, col: 30 },
      {tag_id: 45,  row: 22, col: 37 },
      {tag_id: 46,  row: 22, col: 42 },
      {tag_id: 47,  row: 22, col: 47 },
      {tag_id: 48,  row: 23, col: 10 },
      {tag_id: 49,  row: 23, col: 30 },
      {tag_id: 50,  row: 23, col: 31 },
      {tag_id: 51,  row: 23, col: 32 },
      {tag_id: 52,  row: 23, col: 33 },
      {tag_id: 53,  row: 23, col: 34 },
      {tag_id: 54,  row: 23, col: 35 },
      {tag_id: 55,  row: 23, col: 36 },
      {tag_id: 56,  row: 23, col: 37 },
      {tag_id: 57,  row: 23, col: 38 },
      {tag_id: 58,  row: 23, col: 39 },
      {tag_id: 59,  row: 23, col: 40 },
      {tag_id: 60,  row: 23, col: 41 },
      {tag_id: 61,  row: 23, col: 42 },
      {tag_id: 62,  row: 23, col: 43 },
      {tag_id: 63,  row: 23, col: 44 },
      {tag_id: 64,  row: 23, col: 45 },
      {tag_id: 65,  row: 23, col: 46 },
      {tag_id: 66,  row: 23, col: 47 },
      {tag_id: 67,  row: 24, col: 10 },
      {tag_id: 68,  row: 24, col: 42 },
      {tag_id: 69,  row: 25, col: 10 },
      {tag_id: 70,  row: 25, col: 42 },
      {tag_id: 71,  row: 26, col: 10 },
      {tag_id: 72,  row: 26, col: 42 },
      {tag_id: 73,  row: 27, col: 10 },
      {tag_id: 74,  row: 27, col: 42 },
      {tag_id: 75,  row: 28, col: 10 },
      {tag_id: 76,  row: 28, col: 42 },
      {tag_id: 77,  row: 29, col: 10 },
      {tag_id: 78,  row: 29, col: 42 },
      {tag_id: 79,  row: 30, col: 10 },
      {tag_id: 80,  row: 30, col: 42 },
      {tag_id: 81,  row: 31, col: 10 },
      {tag_id: 82,  row: 31, col: 42 },
      {tag_id: 83,  row: 32, col: 10 },
      {tag_id: 84,  row: 32, col: 42 },
      {tag_id: 85,  row: 33, col: 10 },
      {tag_id: 86,  row: 33, col: 42 },
      {tag_id: 87,  row: 34, col: 10 },
      {tag_id: 88,  row: 34, col: 42 },
      {tag_id: 89,  row: 35, col: 10 },
      {tag_id: 90,  row: 35, col: 11 },
      {tag_id: 91,  row: 35, col: 12 },
      {tag_id: 92,  row: 35, col: 13 },
      {tag_id: 93,  row: 35, col: 14 },
      {tag_id: 94,  row: 35, col: 15 },
      {tag_id: 95,  row: 35, col: 16 },
      {tag_id: 96,  row: 35, col: 17 },
      {tag_id: 97,  row: 35, col: 18 },
      {tag_id: 98,  row: 35, col: 19 },
      {tag_id: 99,  row: 35, col: 20 },
      {tag_id: 100,  row: 35, col: 21 },
      {tag_id: 101,  row: 35, col: 22 },
      {tag_id: 102,  row: 35, col: 23 },
      {tag_id: 103,  row: 35, col: 24 },
      {tag_id: 104,  row: 35, col: 25 },
      {tag_id: 105,  row: 35, col: 26 },
      {tag_id: 106,  row: 35, col: 27 },
      {tag_id: 107,  row: 35, col: 28 },
      {tag_id: 108,  row: 35, col: 29 },
      {tag_id: 109,  row: 35, col: 30 },
      {tag_id: 110,  row: 35, col: 31 },
      {tag_id: 111,  row: 35, col: 32 },
      {tag_id: 112,  row: 35, col: 33 },
      {tag_id: 113,  row: 35, col: 34 },
      {tag_id: 114,  row: 35, col: 35 },
      {tag_id: 115,  row: 35, col: 36 },
      {tag_id: 116,  row: 35, col: 37 },
      {tag_id: 117,  row: 35, col: 38 },
      {tag_id: 118,  row: 35, col: 39 },
      {tag_id: 119,  row: 35, col: 41 },
      {tag_id: 120,  row: 35, col: 42 },
      {tag_id: 121,  row: 35, col: 43 },
      {tag_id: 122,  row: 35, col: 44 },

     {tag_id: 317,  row: 35, col: 45 },

       
      {tag_id: 123,  row: 35, col: 46 },
      {tag_id: 124,  row: 35, col: 47 },
      {tag_id: 125,  row: 36, col: 47 },
      {tag_id: 126,  row: 37, col: 47 },
      {tag_id: 127,  row: 38, col: 47 },
      {tag_id: 128,  row: 39, col: 47 },
      {tag_id: 129,  row: 40, col: 47 },
      {tag_id: 130,  row: 41, col: 47 },
      {tag_id: 131,  row: 42, col: 47 },
      {tag_id: 132,  row: 43, col: 47 },
      {tag_id: 133,  row: 44, col: 47 },
      {tag_id: 134,  row: 45, col: 47 },
      {tag_id: 135,  row: 46, col: 47 },
      {tag_id: 136,  row: 47, col: 47 },
      {tag_id: 137,  row: 48, col: 47 },
      {tag_id: 138,  row: 48, col: 48 },
      {tag_id: 139,  row: 48, col: 49 },
      {tag_id: 140,  row: 48, col: 50 },
      {tag_id: 141,  row: 48, col: 51 },
      {tag_id: 142,  row: 49, col: 51 },
      {tag_id: 143,  row: 50, col: 51 },
      {tag_id: 144,  row: 51, col: 51 },
      {tag_id: 145,  row: 52, col: 51 },
      {tag_id: 146,  row: 53, col: 51 },
      {tag_id: 147,  row: 54, col: 51 },
      {tag_id: 148,  row: 55, col: 51 },
      {tag_id: 149,  row: 56, col: 51 },
      {tag_id: 150,  row: 57, col: 51 },
      {tag_id: 151,  row: 58, col: 16 },
      {tag_id: 152,  row: 58, col: 17 },
      {tag_id: 310,  row: 58, col: 18 },
      {tag_id: 309,  row: 58, col: 19 },
      {tag_id: 153,  row: 58, col: 20 },
      {tag_id: 154,  row: 58, col: 21 },
      {tag_id: 155,  row: 58, col: 22 },
      {tag_id: 156,  row: 58, col: 23 },
      {tag_id: 157,  row: 58, col: 24 },
      {tag_id: 158,  row: 58, col: 25 },
      {tag_id: 159,  row: 58, col: 26 },
      {tag_id: 160,  row: 58, col: 27 },
      {tag_id: 161,  row: 58, col: 28 },
      {tag_id: 162,  row: 58, col: 29 },
      {tag_id: 163,  row: 58, col: 30 },
      {tag_id: 164,  row: 58, col: 31 },
      {tag_id: 165,  row: 58, col: 32 },
      {tag_id: 166,  row: 58, col: 33 },
      {tag_id: 167,  row: 58, col: 34 },
      {tag_id: 168,  row: 58, col: 35 },
      {tag_id: 169,  row: 58, col: 36 },
      {tag_id: 170,  row: 58, col: 37 },
      {tag_id: 171,  row: 58, col: 38 },
      {tag_id: 172,  row: 58, col: 39 },
      {tag_id: 173,  row: 58, col: 40 },
      {tag_id: 174,  row: 58, col: 41 },
      {tag_id: 175,  row: 58, col: 42 },
      {tag_id: 176,  row: 58, col: 43 },
      {tag_id: 177,  row: 58, col: 44 },
      {tag_id: 178,  row: 58, col: 45 },
      {tag_id: 179,  row: 58, col: 46 },
      {tag_id: 180,  row: 58, col: 47 },
      {tag_id: 181,  row: 58, col: 48 },
      {tag_id: 182,  row: 58, col: 49 },
      {tag_id: 183,  row: 58, col: 50 },
      {tag_id: 184,  row: 58, col: 51 },
      {tag_id: 185,  row: 59, col: 16 },
      {tag_id: 186,  row: 59, col: 48 },
      {tag_id: 187,  row: 60, col: 16 },
      {tag_id: 188,  row: 60, col: 48 },
      {tag_id: 189,  row: 61, col: 16 },
      {tag_id: 190,  row: 61, col: 48 },
      {tag_id: 191,  row: 62, col: 16 },
      {tag_id: 192,  row: 63, col: 16 },
      {tag_id: 193,  row: 63, col: 48 },
      {tag_id: 194,  row: 64, col: 16 },
      {tag_id: 195,  row: 64, col: 51 },
      
      {tag_id: 311,  row: 64, col: 50 },
      {tag_id: 312,  row: 64, col: 49 },
      {tag_id: 313,  row: 64, col: 48 },
      
      
      
      
      {tag_id: 196,  row: 64, col: 52 },
      {tag_id: 197,  row: 64, col: 53 },
      {tag_id: 198,  row: 64, col: 54 },
      {tag_id: 199,  row: 64, col: 55 },
      {tag_id: 200,  row: 64, col: 56 },
      {tag_id: 201,  row: 65, col: 16 },
      {tag_id: 202,  row: 65, col: 56 },
      {tag_id: 203,  row: 66, col: 16 },
      {tag_id: 204,  row: 66, col: 56 },
      {tag_id: 205,  row: 67, col: 56 },
      {tag_id: 206,  row: 68, col: 16 },
      {tag_id: 207,  row: 68, col: 56 },
      {tag_id: 208,  row: 69, col: 11 },
      {tag_id: 209,  row: 69, col: 12 },
      {tag_id: 210,  row: 69, col: 13 },
      {tag_id: 211,  row: 69, col: 14 },
      {tag_id: 212,  row: 69, col: 15 },
      {tag_id: 213,  row: 69, col: 16 },
      {tag_id: 214,  row: 69, col: 17 },
      {tag_id: 215,  row: 69, col: 18 },
      {tag_id: 216,  row: 69, col: 19 },
      {tag_id: 217,  row: 69, col: 20 },
      {tag_id: 218,  row: 69, col: 21 },
      {tag_id: 219,  row: 69, col: 56 },
      {tag_id: 220,  row: 70, col: 11 },
      {tag_id: 221,  row: 70, col: 16 },
      {tag_id: 222,  row: 70, col: 21 },
      {tag_id: 223,  row: 70, col: 56 },
      {tag_id: 224,  row: 71, col: 11 },
      {tag_id: 225,  row: 71, col: 16 },
      {tag_id: 226,  row: 71, col: 21 },
      {tag_id: 227,  row: 71, col: 56 },
      {tag_id: 228,  row: 72, col: 11 },
      {tag_id: 229,  row: 72, col: 16 },
      {tag_id: 230,  row: 72, col: 21 },
      {tag_id: 231,  row: 72, col: 56 },
      {tag_id: 232,  row: 73, col: 11 },
      {tag_id: 233,  row: 73, col: 16 },
      {tag_id: 234,  row: 73, col: 21 },
      {tag_id: 235,  row: 73, col: 56 },
      {tag_id: 236,  row: 74, col: 11 },
      {tag_id: 237,  row: 74, col: 16 },
      {tag_id: 238,  row: 74, col: 21 },
      {tag_id: 239,  row: 74, col: 56 },
      {tag_id: 240,  row: 75, col: 11 },
      {tag_id: 241,  row: 75, col: 16 },
      {tag_id: 242,  row: 75, col: 21 },
      {tag_id: 243,  row: 75, col: 56 },
      {tag_id: 244,  row: 76, col: 11 },
      {tag_id: 245,  row: 76, col: 16 },
      {tag_id: 246,  row: 76, col: 21 },
      {tag_id: 247,  row: 76, col: 56 },
      {tag_id: 248,  row: 77, col: 11 },
      {tag_id: 249,  row: 77, col: 16 },
      {tag_id: 250,  row: 77, col: 21 },
      {tag_id: 251,  row: 77, col: 56 },
      {tag_id: 252,  row: 78, col: 11 },
      {tag_id: 253,  row: 78, col: 16 },
      {tag_id: 254,  row: 78, col: 21 },
      {tag_id: 255,  row: 78, col: 56 },
      {tag_id: 256,  row: 79, col: 11 },
      {tag_id: 257,  row: 79, col: 16 },
      {tag_id: 258,  row: 79, col: 21 },
      {tag_id: 259,  row: 79, col: 56 },
      {tag_id: 260,  row: 80, col: 11 },
      {tag_id: 261,  row: 80, col: 16 },
      {tag_id: 262,  row: 80, col: 21 },
      {tag_id: 263,  row: 80, col: 56 },
      {tag_id: 264,  row: 81, col: 11 },
      {tag_id: 265,  row: 81, col: 12 },
      {tag_id: 266,  row: 81, col: 13 },
      {tag_id: 267,  row: 81, col: 14 },
      {tag_id: 268,  row: 81, col: 15 },
      {tag_id: 269,  row: 81, col: 16 },
      {tag_id: 270,  row: 81, col: 17 },
      {tag_id: 271,  row: 81, col: 18 },
      {tag_id: 272,  row: 81, col: 19 },
      {tag_id: 273,  row: 81, col: 20 },
      {tag_id: 274,  row: 81, col: 21 },
      {tag_id: 275,  row: 81, col: 22 },
      {tag_id: 276,  row: 81, col: 23 },
      {tag_id: 277,  row: 81, col: 26 },
      {tag_id: 278,  row: 81, col: 27 },
      {tag_id: 279,  row: 81, col: 28 },
      {tag_id: 280,  row: 81, col: 29 },
      {tag_id: 281,  row: 81, col: 30 },
      {tag_id: 282,  row: 81, col: 31 },
      {tag_id: 283,  row: 81, col: 32 },
      {tag_id: 284,  row: 81, col: 33 },
      {tag_id: 285,  row: 81, col: 34 },
      {tag_id: 286,  row: 81, col: 35 },
      {tag_id: 287,  row: 81, col: 36 },
      {tag_id: 288,  row: 81, col: 37 },
      {tag_id: 289,  row: 81, col: 38 },
      {tag_id: 290,  row: 81, col: 39 },
      {tag_id: 291,  row: 81, col: 40 },
      {tag_id: 292,  row: 81, col: 41 },
      {tag_id: 293,  row: 81, col: 42 },
      {tag_id: 294,  row: 81, col: 43 },
      {tag_id: 295,  row: 81, col: 44 },
      {tag_id: 296,  row: 81, col: 45 },
      {tag_id: 297,  row: 81, col: 46 },
      {tag_id: 298,  row: 81, col: 47 },
      {tag_id: 299,  row: 81, col: 48 },
      {tag_id: 300,  row: 81, col: 49 },
      {tag_id: 301,  row: 81, col: 50 },
      {tag_id: 302,  row: 81, col: 51 },
      {tag_id: 303,  row: 81, col: 52 },
      {tag_id: 304,  row: 81, col: 53 },
      {tag_id: 305,  row: 81, col: 54 },
      {tag_id: 306,  row: 81, col: 55 },
      {tag_id: 307,  row: 81, col: 56 },
   
    ], 
  }
