(cl:in-package wms_data-msg)
(cl:export '(UNIQUE_ID-VAL
          UNIQUE_ID
          DATE-VAL
          DATE
          PRIORITY-VAL
          PRIORITY
          RACK-VAL
          RACK
          SHELF-VAL
          SHELF
          BIN-VAL
          BIN
          ACTION-VAL
          ACTION
          STATUS-VAL
          STATUS
          EAN_CODE-VAL
          EAN_CODE
          PUTAWAY_CODE-VAL
          PUTAWAY_CODE
          ACR_SHELF-VAL
          ACR_SHELF
          WHOLE_BIN_NO-VAL
          WHOLE_BIN_NO
          CORE-VAL
          CORE
          LEVEL-VAL
          LEVEL
          YEAR-VAL
          YEAR
          DATE_DATA-VAL
          DATE_DATA
          SERIAL_NO-VAL
          SERIAL_NO
))