// Auto-generated. Do not edit!

// (in-package qr_mission_scheduler.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let goalMsg = require('./goalMsg.js');

//-----------------------------------------------------------

class mission_schedulerGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goalType = null;
    }
    else {
      if (initObj.hasOwnProperty('goalType')) {
        this.goalType = initObj.goalType
      }
      else {
        this.goalType = new goalMsg();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type mission_schedulerGoal
    // Serialize message field [goalType]
    bufferOffset = goalMsg.serialize(obj.goalType, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type mission_schedulerGoal
    let len;
    let data = new mission_schedulerGoal(null);
    // Deserialize message field [goalType]
    data.goalType = goalMsg.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += goalMsg.getMessageSize(object.goalType);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'qr_mission_scheduler/mission_schedulerGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'dfdc3603f5a1118fa217fb2b770cd9e4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    goalMsg goalType
    
    ================================================================================
    MSG: qr_mission_scheduler/goalMsg
    string goalType
    
    float64 source
    float64 destination
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new mission_schedulerGoal(null);
    if (msg.goalType !== undefined) {
      resolved.goalType = goalMsg.Resolve(msg.goalType)
    }
    else {
      resolved.goalType = new goalMsg()
    }

    return resolved;
    }
};

module.exports = mission_schedulerGoal;
