; Auto-generated. Do not edit!


(cl:in-package anscer_msgs-msg)


;//! \htmlinclude ChargeFeedback.msg.html

(cl:defclass <ChargeFeedback> (roslisp-msg-protocol:ros-message)
  ((charge_feedback
    :reader charge_feedback
    :initarg :charge_feedback
    :type cl:fixnum
    :initform 0)
   (time_elapsed
    :reader time_elapsed
    :initarg :time_elapsed
    :type cl:integer
    :initform 0))
)

(cl:defclass ChargeFeedback (<ChargeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChargeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChargeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name anscer_msgs-msg:<ChargeFeedback> is deprecated: use anscer_msgs-msg:ChargeFeedback instead.")))

(cl:ensure-generic-function 'charge_feedback-val :lambda-list '(m))
(cl:defmethod charge_feedback-val ((m <ChargeFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader anscer_msgs-msg:charge_feedback-val is deprecated.  Use anscer_msgs-msg:charge_feedback instead.")
  (charge_feedback m))

(cl:ensure-generic-function 'time_elapsed-val :lambda-list '(m))
(cl:defmethod time_elapsed-val ((m <ChargeFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader anscer_msgs-msg:time_elapsed-val is deprecated.  Use anscer_msgs-msg:time_elapsed instead.")
  (time_elapsed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChargeFeedback>) ostream)
  "Serializes a message object of type '<ChargeFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'charge_feedback)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'time_elapsed)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChargeFeedback>) istream)
  "Deserializes a message object of type '<ChargeFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'charge_feedback) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'time_elapsed) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChargeFeedback>)))
  "Returns string type for a message object of type '<ChargeFeedback>"
  "anscer_msgs/ChargeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChargeFeedback)))
  "Returns string type for a message object of type 'ChargeFeedback"
  "anscer_msgs/ChargeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChargeFeedback>)))
  "Returns md5sum for a message object of type '<ChargeFeedback>"
  "f3f158ee399b439579a833360d3b32e3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChargeFeedback)))
  "Returns md5sum for a message object of type 'ChargeFeedback"
  "f3f158ee399b439579a833360d3b32e3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChargeFeedback>)))
  "Returns full string definition for message of type '<ChargeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int8 charge_feedback~%int32 time_elapsed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChargeFeedback)))
  "Returns full string definition for message of type 'ChargeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int8 charge_feedback~%int32 time_elapsed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChargeFeedback>))
  (cl:+ 0
     1
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChargeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ChargeFeedback
    (cl:cons ':charge_feedback (charge_feedback msg))
    (cl:cons ':time_elapsed (time_elapsed msg))
))
