; Auto-generated. Do not edit!


(cl:in-package anscer_msgs-msg)


;//! \htmlinclude ChargeGoal.msg.html

(cl:defclass <ChargeGoal> (roslisp-msg-protocol:ros-message)
  ((charge_info
    :reader charge_info
    :initarg :charge_info
    :type anscer_msgs-msg:ChargeInfo
    :initform (cl:make-instance 'anscer_msgs-msg:ChargeInfo)))
)

(cl:defclass ChargeGoal (<ChargeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChargeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChargeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name anscer_msgs-msg:<ChargeGoal> is deprecated: use anscer_msgs-msg:ChargeGoal instead.")))

(cl:ensure-generic-function 'charge_info-val :lambda-list '(m))
(cl:defmethod charge_info-val ((m <ChargeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader anscer_msgs-msg:charge_info-val is deprecated.  Use anscer_msgs-msg:charge_info instead.")
  (charge_info m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChargeGoal>) ostream)
  "Serializes a message object of type '<ChargeGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'charge_info) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChargeGoal>) istream)
  "Deserializes a message object of type '<ChargeGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'charge_info) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChargeGoal>)))
  "Returns string type for a message object of type '<ChargeGoal>"
  "anscer_msgs/ChargeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChargeGoal)))
  "Returns string type for a message object of type 'ChargeGoal"
  "anscer_msgs/ChargeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChargeGoal>)))
  "Returns md5sum for a message object of type '<ChargeGoal>"
  "1e9af38045a149080a90c0719ad06ab1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChargeGoal)))
  "Returns md5sum for a message object of type 'ChargeGoal"
  "1e9af38045a149080a90c0719ad06ab1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChargeGoal>)))
  "Returns full string definition for message of type '<ChargeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%anscer_msgs/ChargeInfo charge_info~%~%================================================================================~%MSG: anscer_msgs/ChargeInfo~%uint8 CONNECTED=1~%uint8 DISCONNECTED=2~%uint8 OVERRIDE=3~%~%bool charger_activate~%int32 charge_time~%bool ignore_time~%float32 charge_percentage~%bool ignore_percentage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChargeGoal)))
  "Returns full string definition for message of type 'ChargeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%anscer_msgs/ChargeInfo charge_info~%~%================================================================================~%MSG: anscer_msgs/ChargeInfo~%uint8 CONNECTED=1~%uint8 DISCONNECTED=2~%uint8 OVERRIDE=3~%~%bool charger_activate~%int32 charge_time~%bool ignore_time~%float32 charge_percentage~%bool ignore_percentage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChargeGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'charge_info))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChargeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ChargeGoal
    (cl:cons ':charge_info (charge_info msg))
))
