; Auto-generated. Do not edit!


(cl:in-package anscer_msgs-msg)


;//! \htmlinclude LiftGoal.msg.html

(cl:defclass <LiftGoal> (roslisp-msg-protocol:ros-message)
  ((system_activate
    :reader system_activate
    :initarg :system_activate
    :type cl:fixnum
    :initform 0))
)

(cl:defclass LiftGoal (<LiftGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LiftGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LiftGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name anscer_msgs-msg:<LiftGoal> is deprecated: use anscer_msgs-msg:LiftGoal instead.")))

(cl:ensure-generic-function 'system_activate-val :lambda-list '(m))
(cl:defmethod system_activate-val ((m <LiftGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader anscer_msgs-msg:system_activate-val is deprecated.  Use anscer_msgs-msg:system_activate instead.")
  (system_activate m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LiftGoal>) ostream)
  "Serializes a message object of type '<LiftGoal>"
  (cl:let* ((signed (cl:slot-value msg 'system_activate)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LiftGoal>) istream)
  "Deserializes a message object of type '<LiftGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'system_activate) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LiftGoal>)))
  "Returns string type for a message object of type '<LiftGoal>"
  "anscer_msgs/LiftGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LiftGoal)))
  "Returns string type for a message object of type 'LiftGoal"
  "anscer_msgs/LiftGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LiftGoal>)))
  "Returns md5sum for a message object of type '<LiftGoal>"
  "233ef4b9a5911ea935e83f06dd24bb45")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LiftGoal)))
  "Returns md5sum for a message object of type 'LiftGoal"
  "233ef4b9a5911ea935e83f06dd24bb45")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LiftGoal>)))
  "Returns full string definition for message of type '<LiftGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int8 system_activate~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LiftGoal)))
  "Returns full string definition for message of type 'LiftGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int8 system_activate~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LiftGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LiftGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LiftGoal
    (cl:cons ':system_activate (system_activate msg))
))
