; Auto-generated. Do not edit!


(cl:in-package anscer_msgs-msg)


;//! \htmlinclude LiftFeedback.msg.html

(cl:defclass <LiftFeedback> (roslisp-msg-protocol:ros-message)
  ((lifter_feedback
    :reader lifter_feedback
    :initarg :lifter_feedback
    :type cl:fixnum
    :initform 0)
   (lifter_status
    :reader lifter_status
    :initarg :lifter_status
    :type cl:string
    :initform ""))
)

(cl:defclass LiftFeedback (<LiftFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LiftFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LiftFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name anscer_msgs-msg:<LiftFeedback> is deprecated: use anscer_msgs-msg:LiftFeedback instead.")))

(cl:ensure-generic-function 'lifter_feedback-val :lambda-list '(m))
(cl:defmethod lifter_feedback-val ((m <LiftFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader anscer_msgs-msg:lifter_feedback-val is deprecated.  Use anscer_msgs-msg:lifter_feedback instead.")
  (lifter_feedback m))

(cl:ensure-generic-function 'lifter_status-val :lambda-list '(m))
(cl:defmethod lifter_status-val ((m <LiftFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader anscer_msgs-msg:lifter_status-val is deprecated.  Use anscer_msgs-msg:lifter_status instead.")
  (lifter_status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LiftFeedback>) ostream)
  "Serializes a message object of type '<LiftFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'lifter_feedback)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'lifter_status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'lifter_status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LiftFeedback>) istream)
  "Deserializes a message object of type '<LiftFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'lifter_feedback) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'lifter_status) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'lifter_status) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LiftFeedback>)))
  "Returns string type for a message object of type '<LiftFeedback>"
  "anscer_msgs/LiftFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LiftFeedback)))
  "Returns string type for a message object of type 'LiftFeedback"
  "anscer_msgs/LiftFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LiftFeedback>)))
  "Returns md5sum for a message object of type '<LiftFeedback>"
  "a765dd01ba96de06700d031b9da4b369")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LiftFeedback)))
  "Returns md5sum for a message object of type 'LiftFeedback"
  "a765dd01ba96de06700d031b9da4b369")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LiftFeedback>)))
  "Returns full string definition for message of type '<LiftFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int8 lifter_feedback~%string lifter_status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LiftFeedback)))
  "Returns full string definition for message of type 'LiftFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int8 lifter_feedback~%string lifter_status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LiftFeedback>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'lifter_status))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LiftFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LiftFeedback
    (cl:cons ':lifter_feedback (lifter_feedback msg))
    (cl:cons ':lifter_status (lifter_status msg))
))
