(cl:in-package graph_creator_msgs-msg)
(cl:export '(ENABLE_FOR_VERTICES-VAL
          ENABLE_FOR_VERTICES
          ENABLE_FOR_EDGES-VAL
          ENABLE_FOR_EDGES
          ENABLE_POSITION_SNAP-VAL
          ENABLE_POSITION_SNAP
          ENABLE_ORIENTATION_SNAP-VAL
          ENABLE_ORIENTATION_SNAP
          POSITION_SNAP_GRID_SIZE-VAL
          POSITION_SNAP_GRID_SIZE
          ORIENTATION_SNAP_ANGLE-VAL
          ORIENTATION_SNAP_ANGLE
))