(cl:in-package graph_creator_msgs-msg)
(cl:export '(GENERATION_TYPE-VAL
          GENERATION_TYPE
          EDGE_CREATION_TYPE-VAL
          EDGE_CREATION_TYPE
          EDGE_DIRECTION_TYPE-VAL
          EDGE_DIRECTION_TYPE
          IGNORE_VERTEX_ORIENTATION-VAL
          IGNORE_VERTEX_ORIENTATION
          USE_EDGE_COUNT_THRESHOLD-VAL
          USE_EDGE_COUNT_THRESHOLD
          EDGE_COUNT_THRESHOLD-VAL
          EDGE_COUNT_THRESHOLD
          DXF_FILE_PATH-VAL
          DXF_FILE_PATH
          SCALE_X-VAL
          SCALE_X
          SCALE_Y-VAL
          SCALE_Y
          START_POSE-VAL
          START_POSE
          ROWS-VAL
          ROWS
          COLUMNS-VAL
          COLUMNS
          ROW_SPACING-VAL
          ROW_SPACING
          COLUMN_SPACING-VAL
          COLUMN_SPACING
))