; Auto-generated. Do not edit!


(cl:in-package qr_mission_scheduler-msg)


;//! \htmlinclude mission_schedulerFeedback.msg.html

(cl:defclass <mission_schedulerFeedback> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass mission_schedulerFeedback (<mission_schedulerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <mission_schedulerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'mission_schedulerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name qr_mission_scheduler-msg:<mission_schedulerFeedback> is deprecated: use qr_mission_scheduler-msg:mission_schedulerFeedback instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <mission_schedulerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader qr_mission_scheduler-msg:pose-val is deprecated.  Use qr_mission_scheduler-msg:pose instead.")
  (pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <mission_schedulerFeedback>) ostream)
  "Serializes a message object of type '<mission_schedulerFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'pose))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'pose))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <mission_schedulerFeedback>) istream)
  "Deserializes a message object of type '<mission_schedulerFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'pose) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'pose)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<mission_schedulerFeedback>)))
  "Returns string type for a message object of type '<mission_schedulerFeedback>"
  "qr_mission_scheduler/mission_schedulerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'mission_schedulerFeedback)))
  "Returns string type for a message object of type 'mission_schedulerFeedback"
  "qr_mission_scheduler/mission_schedulerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<mission_schedulerFeedback>)))
  "Returns md5sum for a message object of type '<mission_schedulerFeedback>"
  "76249fb45cba333e6a82c7f91cfe1879")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'mission_schedulerFeedback)))
  "Returns md5sum for a message object of type 'mission_schedulerFeedback"
  "76249fb45cba333e6a82c7f91cfe1879")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<mission_schedulerFeedback>)))
  "Returns full string definition for message of type '<mission_schedulerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64[]  pose~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'mission_schedulerFeedback)))
  "Returns full string definition for message of type 'mission_schedulerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float64[]  pose~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <mission_schedulerFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'pose) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <mission_schedulerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'mission_schedulerFeedback
    (cl:cons ':pose (pose msg))
))
