// Generated by gencpp from file anscer_msgs/BatteryManagementRequest.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_BATTERYMANAGEMENTREQUEST_H
#define ANSCER_MSGS_MESSAGE_BATTERYMANAGEMENTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace anscer_msgs
{
template <class ContainerAllocator>
struct BatteryManagementRequest_
{
  typedef BatteryManagementRequest_<ContainerAllocator> Type;

  BatteryManagementRequest_()
    : robot_pose()  {
    }
  BatteryManagementRequest_(const ContainerAllocator& _alloc)
    : robot_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _robot_pose_type;
  _robot_pose_type robot_pose;





  typedef boost::shared_ptr< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BatteryManagementRequest_

typedef ::anscer_msgs::BatteryManagementRequest_<std::allocator<void> > BatteryManagementRequest;

typedef boost::shared_ptr< ::anscer_msgs::BatteryManagementRequest > BatteryManagementRequestPtr;
typedef boost::shared_ptr< ::anscer_msgs::BatteryManagementRequest const> BatteryManagementRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator1> & lhs, const ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator2> & rhs)
{
  return lhs.robot_pose == rhs.robot_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator1> & lhs, const ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anscer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1e8e42f88161a7bc7869c4cb33b8e1e";
  }

  static const char* value(const ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1e8e42f88161a7bULL;
  static const uint64_t static_value2 = 0xc7869c4cb33b8e1eULL;
};

template<class ContainerAllocator>
struct DataType< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anscer_msgs/BatteryManagementRequest";
  }

  static const char* value(const ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose robot_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatteryManagementRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anscer_msgs::BatteryManagementRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "robot_pose: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_BATTERYMANAGEMENTREQUEST_H
