// Generated by gencpp from file anscer_msgs/ChargeFeedback.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_CHARGEFEEDBACK_H
#define ANSCER_MSGS_MESSAGE_CHARGEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace anscer_msgs
{
template <class ContainerAllocator>
struct ChargeFeedback_
{
  typedef ChargeFeedback_<ContainerAllocator> Type;

  ChargeFeedback_()
    : charge_feedback(0)
    , time_elapsed(0)  {
    }
  ChargeFeedback_(const ContainerAllocator& _alloc)
    : charge_feedback(0)
    , time_elapsed(0)  {
  (void)_alloc;
    }



   typedef int8_t _charge_feedback_type;
  _charge_feedback_type charge_feedback;

   typedef int32_t _time_elapsed_type;
  _time_elapsed_type time_elapsed;





  typedef boost::shared_ptr< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ChargeFeedback_

typedef ::anscer_msgs::ChargeFeedback_<std::allocator<void> > ChargeFeedback;

typedef boost::shared_ptr< ::anscer_msgs::ChargeFeedback > ChargeFeedbackPtr;
typedef boost::shared_ptr< ::anscer_msgs::ChargeFeedback const> ChargeFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anscer_msgs::ChargeFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anscer_msgs::ChargeFeedback_<ContainerAllocator1> & lhs, const ::anscer_msgs::ChargeFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.charge_feedback == rhs.charge_feedback &&
    lhs.time_elapsed == rhs.time_elapsed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anscer_msgs::ChargeFeedback_<ContainerAllocator1> & lhs, const ::anscer_msgs::ChargeFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anscer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3f158ee399b439579a833360d3b32e3";
  }

  static const char* value(const ::anscer_msgs::ChargeFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3f158ee399b4395ULL;
  static const uint64_t static_value2 = 0x79a833360d3b32e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anscer_msgs/ChargeFeedback";
  }

  static const char* value(const ::anscer_msgs::ChargeFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int8 charge_feedback\n"
"int32 time_elapsed\n"
"\n"
;
  }

  static const char* value(const ::anscer_msgs::ChargeFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.charge_feedback);
      stream.next(m.time_elapsed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChargeFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anscer_msgs::ChargeFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anscer_msgs::ChargeFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "charge_feedback: ";
    Printer<int8_t>::stream(s, indent + "  ", v.charge_feedback);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time_elapsed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.time_elapsed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_CHARGEFEEDBACK_H
