// Generated by gencpp from file anscer_msgs/ChargeAction.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_CHARGEACTION_H
#define ANSCER_MSGS_MESSAGE_CHARGEACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <anscer_msgs/ChargeActionGoal.h>
#include <anscer_msgs/ChargeActionResult.h>
#include <anscer_msgs/ChargeActionFeedback.h>

namespace anscer_msgs
{
template <class ContainerAllocator>
struct ChargeAction_
{
  typedef ChargeAction_<ContainerAllocator> Type;

  ChargeAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  ChargeAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::anscer_msgs::ChargeActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::anscer_msgs::ChargeActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::anscer_msgs::ChargeActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::anscer_msgs::ChargeAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anscer_msgs::ChargeAction_<ContainerAllocator> const> ConstPtr;

}; // struct ChargeAction_

typedef ::anscer_msgs::ChargeAction_<std::allocator<void> > ChargeAction;

typedef boost::shared_ptr< ::anscer_msgs::ChargeAction > ChargeActionPtr;
typedef boost::shared_ptr< ::anscer_msgs::ChargeAction const> ChargeActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anscer_msgs::ChargeAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anscer_msgs::ChargeAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anscer_msgs::ChargeAction_<ContainerAllocator1> & lhs, const ::anscer_msgs::ChargeAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anscer_msgs::ChargeAction_<ContainerAllocator1> & lhs, const ::anscer_msgs::ChargeAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anscer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::ChargeAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::ChargeAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::ChargeAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::ChargeAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::ChargeAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::ChargeAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anscer_msgs::ChargeAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ca840c788c7262fe804c4ec2417109c";
  }

  static const char* value(const ::anscer_msgs::ChargeAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ca840c788c7262fULL;
  static const uint64_t static_value2 = 0xe804c4ec2417109cULL;
};

template<class ContainerAllocator>
struct DataType< ::anscer_msgs::ChargeAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anscer_msgs/ChargeAction";
  }

  static const char* value(const ::anscer_msgs::ChargeAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anscer_msgs::ChargeAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"ChargeActionGoal action_goal\n"
"ChargeActionResult action_result\n"
"ChargeActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: anscer_msgs/ChargeActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ChargeGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: anscer_msgs/ChargeGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"anscer_msgs/ChargeInfo charge_info\n"
"\n"
"================================================================================\n"
"MSG: anscer_msgs/ChargeInfo\n"
"uint8 CONNECTED=1\n"
"uint8 DISCONNECTED=2\n"
"uint8 OVERRIDE=3\n"
"\n"
"bool charger_activate\n"
"int32 charge_time\n"
"bool ignore_time\n"
"float32 charge_percentage\n"
"bool ignore_percentage\n"
"\n"
"================================================================================\n"
"MSG: anscer_msgs/ChargeActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ChargeResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: anscer_msgs/ChargeResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#result definition\n"
"bool is_success\n"
"\n"
"\n"
"================================================================================\n"
"MSG: anscer_msgs/ChargeActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ChargeFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: anscer_msgs/ChargeFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int8 charge_feedback\n"
"int32 time_elapsed\n"
"\n"
;
  }

  static const char* value(const ::anscer_msgs::ChargeAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anscer_msgs::ChargeAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChargeAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anscer_msgs::ChargeAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anscer_msgs::ChargeAction_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "action_goal: ";
    Printer< ::anscer_msgs::ChargeActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_result: ";
    Printer< ::anscer_msgs::ChargeActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "action_feedback: ";
    Printer< ::anscer_msgs::ChargeActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_CHARGEACTION_H
