// Generated by gencpp from file anscer_msgs/ChargeGoal.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_CHARGEGOAL_H
#define ANSCER_MSGS_MESSAGE_CHARGEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <anscer_msgs/ChargeInfo.h>

namespace anscer_msgs
{
template <class ContainerAllocator>
struct ChargeGoal_
{
  typedef ChargeGoal_<ContainerAllocator> Type;

  ChargeGoal_()
    : charge_info()  {
    }
  ChargeGoal_(const ContainerAllocator& _alloc)
    : charge_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::anscer_msgs::ChargeInfo_<ContainerAllocator>  _charge_info_type;
  _charge_info_type charge_info;





  typedef boost::shared_ptr< ::anscer_msgs::ChargeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anscer_msgs::ChargeGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ChargeGoal_

typedef ::anscer_msgs::ChargeGoal_<std::allocator<void> > ChargeGoal;

typedef boost::shared_ptr< ::anscer_msgs::ChargeGoal > ChargeGoalPtr;
typedef boost::shared_ptr< ::anscer_msgs::ChargeGoal const> ChargeGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anscer_msgs::ChargeGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anscer_msgs::ChargeGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anscer_msgs::ChargeGoal_<ContainerAllocator1> & lhs, const ::anscer_msgs::ChargeGoal_<ContainerAllocator2> & rhs)
{
  return lhs.charge_info == rhs.charge_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anscer_msgs::ChargeGoal_<ContainerAllocator1> & lhs, const ::anscer_msgs::ChargeGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anscer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::ChargeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::ChargeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::ChargeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::ChargeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::ChargeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::ChargeGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anscer_msgs::ChargeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e9af38045a149080a90c0719ad06ab1";
  }

  static const char* value(const ::anscer_msgs::ChargeGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e9af38045a14908ULL;
  static const uint64_t static_value2 = 0x0a90c0719ad06ab1ULL;
};

template<class ContainerAllocator>
struct DataType< ::anscer_msgs::ChargeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anscer_msgs/ChargeGoal";
  }

  static const char* value(const ::anscer_msgs::ChargeGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anscer_msgs::ChargeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"anscer_msgs/ChargeInfo charge_info\n"
"\n"
"================================================================================\n"
"MSG: anscer_msgs/ChargeInfo\n"
"uint8 CONNECTED=1\n"
"uint8 DISCONNECTED=2\n"
"uint8 OVERRIDE=3\n"
"\n"
"bool charger_activate\n"
"int32 charge_time\n"
"bool ignore_time\n"
"float32 charge_percentage\n"
"bool ignore_percentage\n"
;
  }

  static const char* value(const ::anscer_msgs::ChargeGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anscer_msgs::ChargeGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.charge_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChargeGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anscer_msgs::ChargeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anscer_msgs::ChargeGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "charge_info: ";
    Printer< ::anscer_msgs::ChargeInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.charge_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_CHARGEGOAL_H
