// Generated by gencpp from file anscer_msgs/HomeLocationResponse.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_HOMELOCATIONRESPONSE_H
#define ANSCER_MSGS_MESSAGE_HOMELOCATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace anscer_msgs
{
template <class ContainerAllocator>
struct HomeLocationResponse_
{
  typedef HomeLocationResponse_<ContainerAllocator> Type;

  HomeLocationResponse_()
    : id(0)
    , is_available(false)  {
    }
  HomeLocationResponse_(const ContainerAllocator& _alloc)
    : id(0)
    , is_available(false)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef uint8_t _is_available_type;
  _is_available_type is_available;





  typedef boost::shared_ptr< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct HomeLocationResponse_

typedef ::anscer_msgs::HomeLocationResponse_<std::allocator<void> > HomeLocationResponse;

typedef boost::shared_ptr< ::anscer_msgs::HomeLocationResponse > HomeLocationResponsePtr;
typedef boost::shared_ptr< ::anscer_msgs::HomeLocationResponse const> HomeLocationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anscer_msgs::HomeLocationResponse_<ContainerAllocator1> & lhs, const ::anscer_msgs::HomeLocationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.is_available == rhs.is_available;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anscer_msgs::HomeLocationResponse_<ContainerAllocator1> & lhs, const ::anscer_msgs::HomeLocationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anscer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f0c260c6a5dba21c42fbd215a65cbeb";
  }

  static const char* value(const ::anscer_msgs::HomeLocationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f0c260c6a5dba21ULL;
  static const uint64_t static_value2 = 0xc42fbd215a65cbebULL;
};

template<class ContainerAllocator>
struct DataType< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anscer_msgs/HomeLocationResponse";
  }

  static const char* value(const ::anscer_msgs::HomeLocationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"bool is_available\n"
"\n"
"\n"
;
  }

  static const char* value(const ::anscer_msgs::HomeLocationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.is_available);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HomeLocationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anscer_msgs::HomeLocationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anscer_msgs::HomeLocationResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_available: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_available);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_HOMELOCATIONRESPONSE_H
