// Generated by gencpp from file anscer_msgs/KeyValue.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_KEYVALUE_H
#define ANSCER_MSGS_MESSAGE_KEYVALUE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace anscer_msgs
{
template <class ContainerAllocator>
struct KeyValue_
{
  typedef KeyValue_<ContainerAllocator> Type;

  KeyValue_()
    : key()
    , value()
    , unit()
    , errorlevel(0.0)  {
    }
  KeyValue_(const ContainerAllocator& _alloc)
    : key(_alloc)
    , value(_alloc)
    , unit(_alloc)
    , errorlevel(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _key_type;
  _key_type key;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _value_type;
  _value_type value;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _unit_type;
  _unit_type unit;

   typedef float _errorlevel_type;
  _errorlevel_type errorlevel;





  typedef boost::shared_ptr< ::anscer_msgs::KeyValue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anscer_msgs::KeyValue_<ContainerAllocator> const> ConstPtr;

}; // struct KeyValue_

typedef ::anscer_msgs::KeyValue_<std::allocator<void> > KeyValue;

typedef boost::shared_ptr< ::anscer_msgs::KeyValue > KeyValuePtr;
typedef boost::shared_ptr< ::anscer_msgs::KeyValue const> KeyValueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anscer_msgs::KeyValue_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anscer_msgs::KeyValue_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anscer_msgs::KeyValue_<ContainerAllocator1> & lhs, const ::anscer_msgs::KeyValue_<ContainerAllocator2> & rhs)
{
  return lhs.key == rhs.key &&
    lhs.value == rhs.value &&
    lhs.unit == rhs.unit &&
    lhs.errorlevel == rhs.errorlevel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anscer_msgs::KeyValue_<ContainerAllocator1> & lhs, const ::anscer_msgs::KeyValue_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anscer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::KeyValue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::KeyValue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::KeyValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::KeyValue_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::KeyValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::KeyValue_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anscer_msgs::KeyValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0366bc3220232a9a18c5cc0865090e86";
  }

  static const char* value(const ::anscer_msgs::KeyValue_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0366bc3220232a9aULL;
  static const uint64_t static_value2 = 0x18c5cc0865090e86ULL;
};

template<class ContainerAllocator>
struct DataType< ::anscer_msgs::KeyValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anscer_msgs/KeyValue";
  }

  static const char* value(const ::anscer_msgs::KeyValue_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anscer_msgs::KeyValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string key			#Label of the value\n"
"string value		#Value to track\n"
"string unit\n"
"float32 errorlevel			#Errorlevel of the value\n"
;
  }

  static const char* value(const ::anscer_msgs::KeyValue_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anscer_msgs::KeyValue_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
      stream.next(m.value);
      stream.next(m.unit);
      stream.next(m.errorlevel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KeyValue_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anscer_msgs::KeyValue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anscer_msgs::KeyValue_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.key);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.value);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "unit: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.unit);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "errorlevel: ";
    Printer<float>::stream(s, indent + "  ", v.errorlevel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_KEYVALUE_H
