// Generated by gencpp from file anscer_msgs/MissionAnalytics.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_MISSIONANALYTICS_H
#define ANSCER_MSGS_MESSAGE_MISSIONANALYTICS_H

#include <ros/service_traits.h>


#include <anscer_msgs/MissionAnalyticsRequest.h>
#include <anscer_msgs/MissionAnalyticsResponse.h>


namespace anscer_msgs
{

struct MissionAnalytics
{

typedef MissionAnalyticsRequest Request;
typedef MissionAnalyticsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionAnalytics
} // namespace anscer_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::anscer_msgs::MissionAnalytics > {
  static const char* value()
  {
    return "08b960482269c6ce2305b1dc4350baa3";
  }

  static const char* value(const ::anscer_msgs::MissionAnalytics&) { return value(); }
};

template<>
struct DataType< ::anscer_msgs::MissionAnalytics > {
  static const char* value()
  {
    return "anscer_msgs/MissionAnalytics";
  }

  static const char* value(const ::anscer_msgs::MissionAnalytics&) { return value(); }
};


// service_traits::MD5Sum< ::anscer_msgs::MissionAnalyticsRequest> should match
// service_traits::MD5Sum< ::anscer_msgs::MissionAnalytics >
template<>
struct MD5Sum< ::anscer_msgs::MissionAnalyticsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::anscer_msgs::MissionAnalytics >::value();
  }
  static const char* value(const ::anscer_msgs::MissionAnalyticsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::anscer_msgs::MissionAnalyticsRequest> should match
// service_traits::DataType< ::anscer_msgs::MissionAnalytics >
template<>
struct DataType< ::anscer_msgs::MissionAnalyticsRequest>
{
  static const char* value()
  {
    return DataType< ::anscer_msgs::MissionAnalytics >::value();
  }
  static const char* value(const ::anscer_msgs::MissionAnalyticsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::anscer_msgs::MissionAnalyticsResponse> should match
// service_traits::MD5Sum< ::anscer_msgs::MissionAnalytics >
template<>
struct MD5Sum< ::anscer_msgs::MissionAnalyticsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::anscer_msgs::MissionAnalytics >::value();
  }
  static const char* value(const ::anscer_msgs::MissionAnalyticsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::anscer_msgs::MissionAnalyticsResponse> should match
// service_traits::DataType< ::anscer_msgs::MissionAnalytics >
template<>
struct DataType< ::anscer_msgs::MissionAnalyticsResponse>
{
  static const char* value()
  {
    return DataType< ::anscer_msgs::MissionAnalytics >::value();
  }
  static const char* value(const ::anscer_msgs::MissionAnalyticsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_MISSIONANALYTICS_H
