// Generated by gencpp from file anscer_msgs/MotorDiagnosticsArray.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_MOTORDIAGNOSTICSARRAY_H
#define ANSCER_MSGS_MESSAGE_MOTORDIAGNOSTICSARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <anscer_msgs/MotorDiagnostics.h>

namespace anscer_msgs
{
template <class ContainerAllocator>
struct MotorDiagnosticsArray_
{
  typedef MotorDiagnosticsArray_<ContainerAllocator> Type;

  MotorDiagnosticsArray_()
    : motor_diagnostics()  {
    }
  MotorDiagnosticsArray_(const ContainerAllocator& _alloc)
    : motor_diagnostics(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::anscer_msgs::MotorDiagnostics_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::anscer_msgs::MotorDiagnostics_<ContainerAllocator> >> _motor_diagnostics_type;
  _motor_diagnostics_type motor_diagnostics;





  typedef boost::shared_ptr< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> const> ConstPtr;

}; // struct MotorDiagnosticsArray_

typedef ::anscer_msgs::MotorDiagnosticsArray_<std::allocator<void> > MotorDiagnosticsArray;

typedef boost::shared_ptr< ::anscer_msgs::MotorDiagnosticsArray > MotorDiagnosticsArrayPtr;
typedef boost::shared_ptr< ::anscer_msgs::MotorDiagnosticsArray const> MotorDiagnosticsArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator1> & lhs, const ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator2> & rhs)
{
  return lhs.motor_diagnostics == rhs.motor_diagnostics;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator1> & lhs, const ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anscer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e04d5a81a4ba18dbd66dc15d7fdf969a";
  }

  static const char* value(const ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe04d5a81a4ba18dbULL;
  static const uint64_t static_value2 = 0xd66dc15d7fdf969aULL;
};

template<class ContainerAllocator>
struct DataType< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anscer_msgs/MotorDiagnosticsArray";
  }

  static const char* value(const ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MotorDiagnostics[] motor_diagnostics\n"
"\n"
"================================================================================\n"
"MSG: anscer_msgs/MotorDiagnostics\n"
"string name\n"
"MotorFaultFlags fault_flags\n"
"MotorStatusFlags status_flags\n"
"\n"
"================================================================================\n"
"MSG: anscer_msgs/MotorFaultFlags\n"
"bool overheat\n"
"bool overvoltage\n"
"bool undervoltage\n"
"bool short_circuit\n"
"bool emergency_stop\n"
"bool motor_setup_fault\n"
"bool mosfet_failure\n"
"bool default_configuration\n"
"\n"
"================================================================================\n"
"MSG: anscer_msgs/MotorStatusFlags\n"
"bool serial_mode\n"
"bool pulse_mode\n"
"bool analog_mode\n"
"bool power_stage_off\n"
"bool stall_detected\n"
"bool at_limit\n"
"bool unused\n"
"bool micro_basic_script_running\n"
"bool motor_tuning_mode\n"
;
  }

  static const char* value(const ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_diagnostics);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorDiagnosticsArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anscer_msgs::MotorDiagnosticsArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "motor_diagnostics: ";
    if (v.motor_diagnostics.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.motor_diagnostics.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::anscer_msgs::MotorDiagnostics_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.motor_diagnostics[i]);
    }
    if (v.motor_diagnostics.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_MOTORDIAGNOSTICSARRAY_H
