// Generated by gencpp from file anscer_msgs/MotorFaultFlags.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_MOTORFAULTFLAGS_H
#define ANSCER_MSGS_MESSAGE_MOTORFAULTFLAGS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace anscer_msgs
{
template <class ContainerAllocator>
struct MotorFaultFlags_
{
  typedef MotorFaultFlags_<ContainerAllocator> Type;

  MotorFaultFlags_()
    : overheat(false)
    , overvoltage(false)
    , undervoltage(false)
    , short_circuit(false)
    , emergency_stop(false)
    , motor_setup_fault(false)
    , mosfet_failure(false)
    , default_configuration(false)  {
    }
  MotorFaultFlags_(const ContainerAllocator& _alloc)
    : overheat(false)
    , overvoltage(false)
    , undervoltage(false)
    , short_circuit(false)
    , emergency_stop(false)
    , motor_setup_fault(false)
    , mosfet_failure(false)
    , default_configuration(false)  {
  (void)_alloc;
    }



   typedef uint8_t _overheat_type;
  _overheat_type overheat;

   typedef uint8_t _overvoltage_type;
  _overvoltage_type overvoltage;

   typedef uint8_t _undervoltage_type;
  _undervoltage_type undervoltage;

   typedef uint8_t _short_circuit_type;
  _short_circuit_type short_circuit;

   typedef uint8_t _emergency_stop_type;
  _emergency_stop_type emergency_stop;

   typedef uint8_t _motor_setup_fault_type;
  _motor_setup_fault_type motor_setup_fault;

   typedef uint8_t _mosfet_failure_type;
  _mosfet_failure_type mosfet_failure;

   typedef uint8_t _default_configuration_type;
  _default_configuration_type default_configuration;





  typedef boost::shared_ptr< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> const> ConstPtr;

}; // struct MotorFaultFlags_

typedef ::anscer_msgs::MotorFaultFlags_<std::allocator<void> > MotorFaultFlags;

typedef boost::shared_ptr< ::anscer_msgs::MotorFaultFlags > MotorFaultFlagsPtr;
typedef boost::shared_ptr< ::anscer_msgs::MotorFaultFlags const> MotorFaultFlagsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anscer_msgs::MotorFaultFlags_<ContainerAllocator1> & lhs, const ::anscer_msgs::MotorFaultFlags_<ContainerAllocator2> & rhs)
{
  return lhs.overheat == rhs.overheat &&
    lhs.overvoltage == rhs.overvoltage &&
    lhs.undervoltage == rhs.undervoltage &&
    lhs.short_circuit == rhs.short_circuit &&
    lhs.emergency_stop == rhs.emergency_stop &&
    lhs.motor_setup_fault == rhs.motor_setup_fault &&
    lhs.mosfet_failure == rhs.mosfet_failure &&
    lhs.default_configuration == rhs.default_configuration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anscer_msgs::MotorFaultFlags_<ContainerAllocator1> & lhs, const ::anscer_msgs::MotorFaultFlags_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anscer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5204cec7a2d19b97b19f5f360556d07a";
  }

  static const char* value(const ::anscer_msgs::MotorFaultFlags_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5204cec7a2d19b97ULL;
  static const uint64_t static_value2 = 0xb19f5f360556d07aULL;
};

template<class ContainerAllocator>
struct DataType< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anscer_msgs/MotorFaultFlags";
  }

  static const char* value(const ::anscer_msgs::MotorFaultFlags_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool overheat\n"
"bool overvoltage\n"
"bool undervoltage\n"
"bool short_circuit\n"
"bool emergency_stop\n"
"bool motor_setup_fault\n"
"bool mosfet_failure\n"
"bool default_configuration\n"
;
  }

  static const char* value(const ::anscer_msgs::MotorFaultFlags_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.overheat);
      stream.next(m.overvoltage);
      stream.next(m.undervoltage);
      stream.next(m.short_circuit);
      stream.next(m.emergency_stop);
      stream.next(m.motor_setup_fault);
      stream.next(m.mosfet_failure);
      stream.next(m.default_configuration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorFaultFlags_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anscer_msgs::MotorFaultFlags_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anscer_msgs::MotorFaultFlags_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "overheat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.overheat);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "overvoltage: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.overvoltage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "undervoltage: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.undervoltage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "short_circuit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.short_circuit);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "emergency_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency_stop);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "motor_setup_fault: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motor_setup_fault);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mosfet_failure: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mosfet_failure);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "default_configuration: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.default_configuration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_MOTORFAULTFLAGS_H
