// Generated by gencpp from file anscer_msgs/NearestNode.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_NEARESTNODE_H
#define ANSCER_MSGS_MESSAGE_NEARESTNODE_H

#include <ros/service_traits.h>


#include <anscer_msgs/NearestNodeRequest.h>
#include <anscer_msgs/NearestNodeResponse.h>


namespace anscer_msgs
{

struct NearestNode
{

typedef NearestNodeRequest Request;
typedef NearestNodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NearestNode
} // namespace anscer_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::anscer_msgs::NearestNode > {
  static const char* value()
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const ::anscer_msgs::NearestNode&) { return value(); }
};

template<>
struct DataType< ::anscer_msgs::NearestNode > {
  static const char* value()
  {
    return "anscer_msgs/NearestNode";
  }

  static const char* value(const ::anscer_msgs::NearestNode&) { return value(); }
};


// service_traits::MD5Sum< ::anscer_msgs::NearestNodeRequest> should match
// service_traits::MD5Sum< ::anscer_msgs::NearestNode >
template<>
struct MD5Sum< ::anscer_msgs::NearestNodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::anscer_msgs::NearestNode >::value();
  }
  static const char* value(const ::anscer_msgs::NearestNodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::anscer_msgs::NearestNodeRequest> should match
// service_traits::DataType< ::anscer_msgs::NearestNode >
template<>
struct DataType< ::anscer_msgs::NearestNodeRequest>
{
  static const char* value()
  {
    return DataType< ::anscer_msgs::NearestNode >::value();
  }
  static const char* value(const ::anscer_msgs::NearestNodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::anscer_msgs::NearestNodeResponse> should match
// service_traits::MD5Sum< ::anscer_msgs::NearestNode >
template<>
struct MD5Sum< ::anscer_msgs::NearestNodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::anscer_msgs::NearestNode >::value();
  }
  static const char* value(const ::anscer_msgs::NearestNodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::anscer_msgs::NearestNodeResponse> should match
// service_traits::DataType< ::anscer_msgs::NearestNode >
template<>
struct DataType< ::anscer_msgs::NearestNodeResponse>
{
  static const char* value()
  {
    return DataType< ::anscer_msgs::NearestNode >::value();
  }
  static const char* value(const ::anscer_msgs::NearestNodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_NEARESTNODE_H
