// Generated by gencpp from file anscer_msgs/RelayState.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_RELAYSTATE_H
#define ANSCER_MSGS_MESSAGE_RELAYSTATE_H

#include <ros/service_traits.h>


#include <anscer_msgs/RelayStateRequest.h>
#include <anscer_msgs/RelayStateResponse.h>


namespace anscer_msgs
{

struct RelayState
{

typedef RelayStateRequest Request;
typedef RelayStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelayState
} // namespace anscer_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::anscer_msgs::RelayState > {
  static const char* value()
  {
    return "e8da6cec6258bbf74a57054e8129516f";
  }

  static const char* value(const ::anscer_msgs::RelayState&) { return value(); }
};

template<>
struct DataType< ::anscer_msgs::RelayState > {
  static const char* value()
  {
    return "anscer_msgs/RelayState";
  }

  static const char* value(const ::anscer_msgs::RelayState&) { return value(); }
};


// service_traits::MD5Sum< ::anscer_msgs::RelayStateRequest> should match
// service_traits::MD5Sum< ::anscer_msgs::RelayState >
template<>
struct MD5Sum< ::anscer_msgs::RelayStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::anscer_msgs::RelayState >::value();
  }
  static const char* value(const ::anscer_msgs::RelayStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::anscer_msgs::RelayStateRequest> should match
// service_traits::DataType< ::anscer_msgs::RelayState >
template<>
struct DataType< ::anscer_msgs::RelayStateRequest>
{
  static const char* value()
  {
    return DataType< ::anscer_msgs::RelayState >::value();
  }
  static const char* value(const ::anscer_msgs::RelayStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::anscer_msgs::RelayStateResponse> should match
// service_traits::MD5Sum< ::anscer_msgs::RelayState >
template<>
struct MD5Sum< ::anscer_msgs::RelayStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::anscer_msgs::RelayState >::value();
  }
  static const char* value(const ::anscer_msgs::RelayStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::anscer_msgs::RelayStateResponse> should match
// service_traits::DataType< ::anscer_msgs::RelayState >
template<>
struct DataType< ::anscer_msgs::RelayStateResponse>
{
  static const char* value()
  {
    return DataType< ::anscer_msgs::RelayState >::value();
  }
  static const char* value(const ::anscer_msgs::RelayStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_RELAYSTATE_H
