// Generated by gencpp from file anscer_msgs/RelayStateRequest.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_RELAYSTATEREQUEST_H
#define ANSCER_MSGS_MESSAGE_RELAYSTATEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace anscer_msgs
{
template <class ContainerAllocator>
struct RelayStateRequest_
{
  typedef RelayStateRequest_<ContainerAllocator> Type;

  RelayStateRequest_()
    : relay_state(false)  {
    }
  RelayStateRequest_(const ContainerAllocator& _alloc)
    : relay_state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _relay_state_type;
  _relay_state_type relay_state;





  typedef boost::shared_ptr< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RelayStateRequest_

typedef ::anscer_msgs::RelayStateRequest_<std::allocator<void> > RelayStateRequest;

typedef boost::shared_ptr< ::anscer_msgs::RelayStateRequest > RelayStateRequestPtr;
typedef boost::shared_ptr< ::anscer_msgs::RelayStateRequest const> RelayStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::anscer_msgs::RelayStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::anscer_msgs::RelayStateRequest_<ContainerAllocator1> & lhs, const ::anscer_msgs::RelayStateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.relay_state == rhs.relay_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::anscer_msgs::RelayStateRequest_<ContainerAllocator1> & lhs, const ::anscer_msgs::RelayStateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace anscer_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2595becfbff65117e98324b487107fa0";
  }

  static const char* value(const ::anscer_msgs::RelayStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2595becfbff65117ULL;
  static const uint64_t static_value2 = 0xe98324b487107fa0ULL;
};

template<class ContainerAllocator>
struct DataType< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "anscer_msgs/RelayStateRequest";
  }

  static const char* value(const ::anscer_msgs::RelayStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool relay_state\n"
;
  }

  static const char* value(const ::anscer_msgs::RelayStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.relay_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelayStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::anscer_msgs::RelayStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::anscer_msgs::RelayStateRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "relay_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relay_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_RELAYSTATEREQUEST_H
