// Generated by gencpp from file anscer_msgs/ShelfReader.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_SHELFREADER_H
#define ANSCER_MSGS_MESSAGE_SHELFREADER_H

#include <ros/service_traits.h>


#include <anscer_msgs/ShelfReaderRequest.h>
#include <anscer_msgs/ShelfReaderResponse.h>


namespace anscer_msgs
{

struct ShelfReader
{

typedef ShelfReaderRequest Request;
typedef ShelfReaderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ShelfReader
} // namespace anscer_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::anscer_msgs::ShelfReader > {
  static const char* value()
  {
    return "4218f5cbbe42113a859058f65a58f219";
  }

  static const char* value(const ::anscer_msgs::ShelfReader&) { return value(); }
};

template<>
struct DataType< ::anscer_msgs::ShelfReader > {
  static const char* value()
  {
    return "anscer_msgs/ShelfReader";
  }

  static const char* value(const ::anscer_msgs::ShelfReader&) { return value(); }
};


// service_traits::MD5Sum< ::anscer_msgs::ShelfReaderRequest> should match
// service_traits::MD5Sum< ::anscer_msgs::ShelfReader >
template<>
struct MD5Sum< ::anscer_msgs::ShelfReaderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::anscer_msgs::ShelfReader >::value();
  }
  static const char* value(const ::anscer_msgs::ShelfReaderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::anscer_msgs::ShelfReaderRequest> should match
// service_traits::DataType< ::anscer_msgs::ShelfReader >
template<>
struct DataType< ::anscer_msgs::ShelfReaderRequest>
{
  static const char* value()
  {
    return DataType< ::anscer_msgs::ShelfReader >::value();
  }
  static const char* value(const ::anscer_msgs::ShelfReaderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::anscer_msgs::ShelfReaderResponse> should match
// service_traits::MD5Sum< ::anscer_msgs::ShelfReader >
template<>
struct MD5Sum< ::anscer_msgs::ShelfReaderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::anscer_msgs::ShelfReader >::value();
  }
  static const char* value(const ::anscer_msgs::ShelfReaderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::anscer_msgs::ShelfReaderResponse> should match
// service_traits::DataType< ::anscer_msgs::ShelfReader >
template<>
struct DataType< ::anscer_msgs::ShelfReaderResponse>
{
  static const char* value()
  {
    return DataType< ::anscer_msgs::ShelfReader >::value();
  }
  static const char* value(const ::anscer_msgs::ShelfReaderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_SHELFREADER_H
