// Generated by gencpp from file anscer_msgs/TripAnalytics.msg
// DO NOT EDIT!


#ifndef ANSCER_MSGS_MESSAGE_TRIPANALYTICS_H
#define ANSCER_MSGS_MESSAGE_TRIPANALYTICS_H

#include <ros/service_traits.h>


#include <anscer_msgs/TripAnalyticsRequest.h>
#include <anscer_msgs/TripAnalyticsResponse.h>


namespace anscer_msgs
{

struct TripAnalytics
{

typedef TripAnalyticsRequest Request;
typedef TripAnalyticsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TripAnalytics
} // namespace anscer_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::anscer_msgs::TripAnalytics > {
  static const char* value()
  {
    return "08b960482269c6ce2305b1dc4350baa3";
  }

  static const char* value(const ::anscer_msgs::TripAnalytics&) { return value(); }
};

template<>
struct DataType< ::anscer_msgs::TripAnalytics > {
  static const char* value()
  {
    return "anscer_msgs/TripAnalytics";
  }

  static const char* value(const ::anscer_msgs::TripAnalytics&) { return value(); }
};


// service_traits::MD5Sum< ::anscer_msgs::TripAnalyticsRequest> should match
// service_traits::MD5Sum< ::anscer_msgs::TripAnalytics >
template<>
struct MD5Sum< ::anscer_msgs::TripAnalyticsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::anscer_msgs::TripAnalytics >::value();
  }
  static const char* value(const ::anscer_msgs::TripAnalyticsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::anscer_msgs::TripAnalyticsRequest> should match
// service_traits::DataType< ::anscer_msgs::TripAnalytics >
template<>
struct DataType< ::anscer_msgs::TripAnalyticsRequest>
{
  static const char* value()
  {
    return DataType< ::anscer_msgs::TripAnalytics >::value();
  }
  static const char* value(const ::anscer_msgs::TripAnalyticsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::anscer_msgs::TripAnalyticsResponse> should match
// service_traits::MD5Sum< ::anscer_msgs::TripAnalytics >
template<>
struct MD5Sum< ::anscer_msgs::TripAnalyticsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::anscer_msgs::TripAnalytics >::value();
  }
  static const char* value(const ::anscer_msgs::TripAnalyticsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::anscer_msgs::TripAnalyticsResponse> should match
// service_traits::DataType< ::anscer_msgs::TripAnalytics >
template<>
struct DataType< ::anscer_msgs::TripAnalyticsResponse>
{
  static const char* value()
  {
    return DataType< ::anscer_msgs::TripAnalytics >::value();
  }
  static const char* value(const ::anscer_msgs::TripAnalyticsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ANSCER_MSGS_MESSAGE_TRIPANALYTICS_H
