// Generated by gencpp from file lift_action/Home_sensor.msg
// DO NOT EDIT!


#ifndef LIFT_ACTION_MESSAGE_HOME_SENSOR_H
#define LIFT_ACTION_MESSAGE_HOME_SENSOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lift_action
{
template <class ContainerAllocator>
struct Home_sensor_
{
  typedef Home_sensor_<ContainerAllocator> Type;

  Home_sensor_()
    : process()
    , homingStatus(false)  {
    }
  Home_sensor_(const ContainerAllocator& _alloc)
    : process(_alloc)
    , homingStatus(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _process_type;
  _process_type process;

   typedef uint8_t _homingStatus_type;
  _homingStatus_type homingStatus;





  typedef boost::shared_ptr< ::lift_action::Home_sensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lift_action::Home_sensor_<ContainerAllocator> const> ConstPtr;

}; // struct Home_sensor_

typedef ::lift_action::Home_sensor_<std::allocator<void> > Home_sensor;

typedef boost::shared_ptr< ::lift_action::Home_sensor > Home_sensorPtr;
typedef boost::shared_ptr< ::lift_action::Home_sensor const> Home_sensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lift_action::Home_sensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lift_action::Home_sensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lift_action::Home_sensor_<ContainerAllocator1> & lhs, const ::lift_action::Home_sensor_<ContainerAllocator2> & rhs)
{
  return lhs.process == rhs.process &&
    lhs.homingStatus == rhs.homingStatus;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lift_action::Home_sensor_<ContainerAllocator1> & lhs, const ::lift_action::Home_sensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lift_action

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lift_action::Home_sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lift_action::Home_sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lift_action::Home_sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lift_action::Home_sensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lift_action::Home_sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lift_action::Home_sensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lift_action::Home_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4558b3f32ba7b3eceae2851b267cf424";
  }

  static const char* value(const ::lift_action::Home_sensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4558b3f32ba7b3ecULL;
  static const uint64_t static_value2 = 0xeae2851b267cf424ULL;
};

template<class ContainerAllocator>
struct DataType< ::lift_action::Home_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lift_action/Home_sensor";
  }

  static const char* value(const ::lift_action::Home_sensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lift_action::Home_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string process\n"
"bool homingStatus\n"
;
  }

  static const char* value(const ::lift_action::Home_sensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lift_action::Home_sensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.process);
      stream.next(m.homingStatus);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Home_sensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lift_action::Home_sensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lift_action::Home_sensor_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "process: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.process);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "homingStatus: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.homingStatus);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIFT_ACTION_MESSAGE_HOME_SENSOR_H
