// Generated by gencpp from file graph_creator_msgs/EdgeCreationType.msg
// DO NOT EDIT!


#ifndef GRAPH_CREATOR_MSGS_MESSAGE_EDGECREATIONTYPE_H
#define GRAPH_CREATOR_MSGS_MESSAGE_EDGECREATIONTYPE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace graph_creator_msgs
{
template <class ContainerAllocator>
struct EdgeCreationType_
{
  typedef EdgeCreationType_<ContainerAllocator> Type;

  EdgeCreationType_()
    : type(0)  {
    }
  EdgeCreationType_(const ContainerAllocator& _alloc)
    : type(0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(EDGE_CREATION_TYPE_STRAIGHT_LINE)
  #undef EDGE_CREATION_TYPE_STRAIGHT_LINE
#endif
#if defined(_WIN32) && defined(EDGE_CREATION_TYPE_CUBIC_BEZIER)
  #undef EDGE_CREATION_TYPE_CUBIC_BEZIER
#endif

  enum {
    EDGE_CREATION_TYPE_STRAIGHT_LINE = 0u,
    EDGE_CREATION_TYPE_CUBIC_BEZIER = 1u,
  };


  typedef boost::shared_ptr< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> const> ConstPtr;

}; // struct EdgeCreationType_

typedef ::graph_creator_msgs::EdgeCreationType_<std::allocator<void> > EdgeCreationType;

typedef boost::shared_ptr< ::graph_creator_msgs::EdgeCreationType > EdgeCreationTypePtr;
typedef boost::shared_ptr< ::graph_creator_msgs::EdgeCreationType const> EdgeCreationTypeConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator1> & lhs, const ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator1> & lhs, const ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graph_creator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca84d608a8d470273fdf849e3d46708a";
  }

  static const char* value(const ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca84d608a8d47027ULL;
  static const uint64_t static_value2 = 0x3fdf849e3d46708aULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_creator_msgs/EdgeCreationType";
  }

  static const char* value(const ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 EDGE_CREATION_TYPE_STRAIGHT_LINE=0\n"
"uint8 EDGE_CREATION_TYPE_CUBIC_BEZIER=1\n"
"\n"
"uint8 type\n"
;
  }

  static const char* value(const ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EdgeCreationType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_creator_msgs::EdgeCreationType_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_CREATOR_MSGS_MESSAGE_EDGECREATIONTYPE_H
