// Generated by gencpp from file graph_creator_msgs/SetEdgeDirectionCreationType.msg
// DO NOT EDIT!


#ifndef GRAPH_CREATOR_MSGS_MESSAGE_SETEDGEDIRECTIONCREATIONTYPE_H
#define GRAPH_CREATOR_MSGS_MESSAGE_SETEDGEDIRECTIONCREATIONTYPE_H

#include <ros/service_traits.h>


#include <graph_creator_msgs/SetEdgeDirectionCreationTypeRequest.h>
#include <graph_creator_msgs/SetEdgeDirectionCreationTypeResponse.h>


namespace graph_creator_msgs
{

struct SetEdgeDirectionCreationType
{

typedef SetEdgeDirectionCreationTypeRequest Request;
typedef SetEdgeDirectionCreationTypeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEdgeDirectionCreationType
} // namespace graph_creator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graph_creator_msgs::SetEdgeDirectionCreationType > {
  static const char* value()
  {
    return "34f28652b2a44e6592bf32db0fa65269";
  }

  static const char* value(const ::graph_creator_msgs::SetEdgeDirectionCreationType&) { return value(); }
};

template<>
struct DataType< ::graph_creator_msgs::SetEdgeDirectionCreationType > {
  static const char* value()
  {
    return "graph_creator_msgs/SetEdgeDirectionCreationType";
  }

  static const char* value(const ::graph_creator_msgs::SetEdgeDirectionCreationType&) { return value(); }
};


// service_traits::MD5Sum< ::graph_creator_msgs::SetEdgeDirectionCreationTypeRequest> should match
// service_traits::MD5Sum< ::graph_creator_msgs::SetEdgeDirectionCreationType >
template<>
struct MD5Sum< ::graph_creator_msgs::SetEdgeDirectionCreationTypeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graph_creator_msgs::SetEdgeDirectionCreationType >::value();
  }
  static const char* value(const ::graph_creator_msgs::SetEdgeDirectionCreationTypeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_creator_msgs::SetEdgeDirectionCreationTypeRequest> should match
// service_traits::DataType< ::graph_creator_msgs::SetEdgeDirectionCreationType >
template<>
struct DataType< ::graph_creator_msgs::SetEdgeDirectionCreationTypeRequest>
{
  static const char* value()
  {
    return DataType< ::graph_creator_msgs::SetEdgeDirectionCreationType >::value();
  }
  static const char* value(const ::graph_creator_msgs::SetEdgeDirectionCreationTypeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graph_creator_msgs::SetEdgeDirectionCreationTypeResponse> should match
// service_traits::MD5Sum< ::graph_creator_msgs::SetEdgeDirectionCreationType >
template<>
struct MD5Sum< ::graph_creator_msgs::SetEdgeDirectionCreationTypeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graph_creator_msgs::SetEdgeDirectionCreationType >::value();
  }
  static const char* value(const ::graph_creator_msgs::SetEdgeDirectionCreationTypeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_creator_msgs::SetEdgeDirectionCreationTypeResponse> should match
// service_traits::DataType< ::graph_creator_msgs::SetEdgeDirectionCreationType >
template<>
struct DataType< ::graph_creator_msgs::SetEdgeDirectionCreationTypeResponse>
{
  static const char* value()
  {
    return DataType< ::graph_creator_msgs::SetEdgeDirectionCreationType >::value();
  }
  static const char* value(const ::graph_creator_msgs::SetEdgeDirectionCreationTypeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRAPH_CREATOR_MSGS_MESSAGE_SETEDGEDIRECTIONCREATIONTYPE_H
