(cl:in-package graph_msgs-msg)
(cl:export '(NAME-VAL
          NAME
          ALIAS-VAL
          ALIAS
          TYPE-VAL
          TYPE
          EDGE_DIRECTION_TYPE-VAL
          EDGE_DIRECTION_TYPE
          CREATION_TYPE-VAL
          CREATION_TYPE
          SOURCE_VERTEX_ID-VAL
          SOURCE_VERTEX_ID
          TARGET_VERTEX_ID-VAL
          TARGET_VERTEX_ID
          LENGTH-VAL
          LENGTH
          COST_FACTOR-VAL
          COST_FACTOR
          BIDIRECTIONAL-VAL
          BIDIRECTIONAL
          INDEPENDENT_ORIENTATION-VAL
          INDEPENDENT_ORIENTATION
          CONTROL_POINTS-VAL
          CONTROL_POINTS
          CONTROL_ORIENTATION-VAL
          CONTROL_ORIENTATION
          POSES-VAL
          POSES
          PROPERTIES-VAL
          PROPERTIES
))