// Auto-generated. Do not edit!

// (in-package anscer_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class ProcessFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.system_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('system_feedback')) {
        this.system_feedback = initObj.system_feedback
      }
      else {
        this.system_feedback = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type ProcessFeedback
    // Serialize message field [system_feedback]
    bufferOffset = _serializer.bool(obj.system_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type ProcessFeedback
    let len;
    let data = new ProcessFeedback(null);
    // Deserialize message field [system_feedback]
    data.system_feedback = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'anscer_msgs/ProcessFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '418131b84a5b726f697bf57cf5fd871f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    bool system_feedback
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new ProcessFeedback(null);
    if (msg.system_feedback !== undefined) {
      resolved.system_feedback = msg.system_feedback;
    }
    else {
      resolved.system_feedback = false
    }

    return resolved;
    }
};

module.exports = ProcessFeedback;
