// Generated by gencpp from file qr_mission_scheduler/GetGoalRequest.msg
// DO NOT EDIT!


#ifndef QR_MISSION_SCHEDULER_MESSAGE_GETGOALREQUEST_H
#define QR_MISSION_SCHEDULER_MESSAGE_GETGOALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qr_mission_scheduler
{
template <class ContainerAllocator>
struct GetGoalRequest_
{
  typedef GetGoalRequest_<ContainerAllocator> Type;

  GetGoalRequest_()
    : goalType()
    , source_id(0.0)
    , target_id(0.0)  {
    }
  GetGoalRequest_(const ContainerAllocator& _alloc)
    : goalType(_alloc)
    , source_id(0.0)
    , target_id(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _goalType_type;
  _goalType_type goalType;

   typedef double _source_id_type;
  _source_id_type source_id;

   typedef double _target_id_type;
  _target_id_type target_id;





  typedef boost::shared_ptr< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetGoalRequest_

typedef ::qr_mission_scheduler::GetGoalRequest_<std::allocator<void> > GetGoalRequest;

typedef boost::shared_ptr< ::qr_mission_scheduler::GetGoalRequest > GetGoalRequestPtr;
typedef boost::shared_ptr< ::qr_mission_scheduler::GetGoalRequest const> GetGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator1> & lhs, const ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goalType == rhs.goalType &&
    lhs.source_id == rhs.source_id &&
    lhs.target_id == rhs.target_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator1> & lhs, const ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qr_mission_scheduler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2f8e68b25673e07d8c78993888f0d45";
  }

  static const char* value(const ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2f8e68b25673e07ULL;
  static const uint64_t static_value2 = 0xd8c78993888f0d45ULL;
};

template<class ContainerAllocator>
struct DataType< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qr_mission_scheduler/GetGoalRequest";
  }

  static const char* value(const ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Source and destination IDs\n"
"string goalType\n"
"float64 source_id\n"
"float64 target_id\n"
"\n"
;
  }

  static const char* value(const ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goalType);
      stream.next(m.source_id);
      stream.next(m.target_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qr_mission_scheduler::GetGoalRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "goalType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.goalType);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source_id: ";
    Printer<double>::stream(s, indent + "  ", v.source_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_id: ";
    Printer<double>::stream(s, indent + "  ", v.target_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QR_MISSION_SCHEDULER_MESSAGE_GETGOALREQUEST_H
