// Generated by gencpp from file qr_mission_scheduler/goalMsg.msg
// DO NOT EDIT!


#ifndef QR_MISSION_SCHEDULER_MESSAGE_GOALMSG_H
#define QR_MISSION_SCHEDULER_MESSAGE_GOALMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qr_mission_scheduler
{
template <class ContainerAllocator>
struct goalMsg_
{
  typedef goalMsg_<ContainerAllocator> Type;

  goalMsg_()
    : goalType()
    , source(0.0)
    , destination(0.0)  {
    }
  goalMsg_(const ContainerAllocator& _alloc)
    : goalType(_alloc)
    , source(0.0)
    , destination(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _goalType_type;
  _goalType_type goalType;

   typedef double _source_type;
  _source_type source;

   typedef double _destination_type;
  _destination_type destination;





  typedef boost::shared_ptr< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> const> ConstPtr;

}; // struct goalMsg_

typedef ::qr_mission_scheduler::goalMsg_<std::allocator<void> > goalMsg;

typedef boost::shared_ptr< ::qr_mission_scheduler::goalMsg > goalMsgPtr;
typedef boost::shared_ptr< ::qr_mission_scheduler::goalMsg const> goalMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qr_mission_scheduler::goalMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qr_mission_scheduler::goalMsg_<ContainerAllocator1> & lhs, const ::qr_mission_scheduler::goalMsg_<ContainerAllocator2> & rhs)
{
  return lhs.goalType == rhs.goalType &&
    lhs.source == rhs.source &&
    lhs.destination == rhs.destination;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qr_mission_scheduler::goalMsg_<ContainerAllocator1> & lhs, const ::qr_mission_scheduler::goalMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qr_mission_scheduler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bdc5d71ceffd1361f6883e493cc747c6";
  }

  static const char* value(const ::qr_mission_scheduler::goalMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbdc5d71ceffd1361ULL;
  static const uint64_t static_value2 = 0xf6883e493cc747c6ULL;
};

template<class ContainerAllocator>
struct DataType< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qr_mission_scheduler/goalMsg";
  }

  static const char* value(const ::qr_mission_scheduler::goalMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string goalType\n"
"\n"
"float64 source\n"
"float64 destination\n"
"\n"
;
  }

  static const char* value(const ::qr_mission_scheduler::goalMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goalType);
      stream.next(m.source);
      stream.next(m.destination);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goalMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qr_mission_scheduler::goalMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qr_mission_scheduler::goalMsg_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "goalType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.goalType);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "source: ";
    Printer<double>::stream(s, indent + "  ", v.source);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "destination: ";
    Printer<double>::stream(s, indent + "  ", v.destination);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QR_MISSION_SCHEDULER_MESSAGE_GOALMSG_H
