// Generated by gencpp from file qr_mission_scheduler/mission_schedulerFeedback.msg
// DO NOT EDIT!


#ifndef QR_MISSION_SCHEDULER_MESSAGE_MISSION_SCHEDULERFEEDBACK_H
#define QR_MISSION_SCHEDULER_MESSAGE_MISSION_SCHEDULERFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qr_mission_scheduler
{
template <class ContainerAllocator>
struct mission_schedulerFeedback_
{
  typedef mission_schedulerFeedback_<ContainerAllocator> Type;

  mission_schedulerFeedback_()
    : pose()  {
    }
  mission_schedulerFeedback_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct mission_schedulerFeedback_

typedef ::qr_mission_scheduler::mission_schedulerFeedback_<std::allocator<void> > mission_schedulerFeedback;

typedef boost::shared_ptr< ::qr_mission_scheduler::mission_schedulerFeedback > mission_schedulerFeedbackPtr;
typedef boost::shared_ptr< ::qr_mission_scheduler::mission_schedulerFeedback const> mission_schedulerFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator1> & lhs, const ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator1> & lhs, const ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qr_mission_scheduler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76249fb45cba333e6a82c7f91cfe1879";
  }

  static const char* value(const ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76249fb45cba333eULL;
  static const uint64_t static_value2 = 0x6a82c7f91cfe1879ULL;
};

template<class ContainerAllocator>
struct DataType< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qr_mission_scheduler/mission_schedulerFeedback";
  }

  static const char* value(const ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"float64[]  pose\n"
"\n"
;
  }

  static const char* value(const ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mission_schedulerFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qr_mission_scheduler::mission_schedulerFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    if (v.pose.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.pose[i]);
    }
    if (v.pose.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // QR_MISSION_SCHEDULER_MESSAGE_MISSION_SCHEDULERFEEDBACK_H
