acr_robot_controller:
  ros__parameters:
    # Controller configuration
    controller_type: 1
    # Robot parameters with dot notation (flattened)
    robot.wheel_seperation: 0.90
    robot.wheel_radius: 0.101
    robot.TPR: 16384.0
    robot.linear_vel_limit: 3.0
    robot.angular_vel_limit: 1.0
    robot.gearRatio: 9.0
    robot.odom_frame: "odom_frame"
    robot.base_frame: "base_footprint"
    robot.barcode_global_topic: "barcode/global"
    robot.debug_cmd_topic: "debug/cmd_vel"
    # Frame IDs (top-level)
    odom_frame: "odom_frame"
    base_frame: "base_footprint"
    # Topic names
    cmd_topic: "cmd_vel"
    odom_topic: "odom"
    emergency_stop_topic: "e_stop"
    battery_topic: "bms_data/battery_state"
    motor_diagnostics_topic: "motor_diagnostics"
    # Timeouts
    cmd_vel_timeout: 0.5
    # TF publishing
    publish_tf: true
    # Serial port
    roboteq_port: "/dev/roboteq"
