// Generated by gencpp from file graph_msgs/GetGraphPlan.msg
// DO NOT EDIT!


#ifndef GRAPH_MSGS_MESSAGE_GETGRAPHPLAN_H
#define GRAPH_MSGS_MESSAGE_GETGRAPHPLAN_H

#include <ros/service_traits.h>


#include <graph_msgs/GetGraphPlanRequest.h>
#include <graph_msgs/GetGraphPlanResponse.h>


namespace graph_msgs
{

struct GetGraphPlan
{

typedef GetGraphPlanRequest Request;
typedef GetGraphPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGraphPlan
} // namespace graph_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graph_msgs::GetGraphPlan > {
  static const char* value()
  {
    return "246031edd693b7aff99fb77edb89c199";
  }

  static const char* value(const ::graph_msgs::GetGraphPlan&) { return value(); }
};

template<>
struct DataType< ::graph_msgs::GetGraphPlan > {
  static const char* value()
  {
    return "graph_msgs/GetGraphPlan";
  }

  static const char* value(const ::graph_msgs::GetGraphPlan&) { return value(); }
};


// service_traits::MD5Sum< ::graph_msgs::GetGraphPlanRequest> should match
// service_traits::MD5Sum< ::graph_msgs::GetGraphPlan >
template<>
struct MD5Sum< ::graph_msgs::GetGraphPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graph_msgs::GetGraphPlan >::value();
  }
  static const char* value(const ::graph_msgs::GetGraphPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_msgs::GetGraphPlanRequest> should match
// service_traits::DataType< ::graph_msgs::GetGraphPlan >
template<>
struct DataType< ::graph_msgs::GetGraphPlanRequest>
{
  static const char* value()
  {
    return DataType< ::graph_msgs::GetGraphPlan >::value();
  }
  static const char* value(const ::graph_msgs::GetGraphPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graph_msgs::GetGraphPlanResponse> should match
// service_traits::MD5Sum< ::graph_msgs::GetGraphPlan >
template<>
struct MD5Sum< ::graph_msgs::GetGraphPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graph_msgs::GetGraphPlan >::value();
  }
  static const char* value(const ::graph_msgs::GetGraphPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_msgs::GetGraphPlanResponse> should match
// service_traits::DataType< ::graph_msgs::GetGraphPlan >
template<>
struct DataType< ::graph_msgs::GetGraphPlanResponse>
{
  static const char* value()
  {
    return DataType< ::graph_msgs::GetGraphPlan >::value();
  }
  static const char* value(const ::graph_msgs::GetGraphPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRAPH_MSGS_MESSAGE_GETGRAPHPLAN_H
