// Generated by gencpp from file graph_msgs/LoadGraphResponse.msg
// DO NOT EDIT!


#ifndef GRAPH_MSGS_MESSAGE_LOADGRAPHRESPONSE_H
#define GRAPH_MSGS_MESSAGE_LOADGRAPHRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <graph_msgs/Graph.h>

namespace graph_msgs
{
template <class ContainerAllocator>
struct LoadGraphResponse_
{
  typedef LoadGraphResponse_<ContainerAllocator> Type;

  LoadGraphResponse_()
    : graph()
    , result(0)  {
    }
  LoadGraphResponse_(const ContainerAllocator& _alloc)
    : graph(_alloc)
    , result(0)  {
  (void)_alloc;
    }



   typedef  ::graph_msgs::Graph_<ContainerAllocator>  _graph_type;
  _graph_type graph;

   typedef uint8_t _result_type;
  _result_type result;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(RESULT_SUCCESS)
  #undef RESULT_SUCCESS
#endif
#if defined(_WIN32) && defined(RESULT_GRAPH_DOES_NOT_EXIST)
  #undef RESULT_GRAPH_DOES_NOT_EXIST
#endif
#if defined(_WIN32) && defined(RESULT_INVALID_GRAPH_FILE_PATH)
  #undef RESULT_INVALID_GRAPH_FILE_PATH
#endif
#if defined(_WIN32) && defined(RESULT_UNDEFINED_FAILURE)
  #undef RESULT_UNDEFINED_FAILURE
#endif

  enum {
    RESULT_SUCCESS = 0u,
    RESULT_GRAPH_DOES_NOT_EXIST = 1u,
    RESULT_INVALID_GRAPH_FILE_PATH = 2u,
    RESULT_UNDEFINED_FAILURE = 255u,
  };


  typedef boost::shared_ptr< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LoadGraphResponse_

typedef ::graph_msgs::LoadGraphResponse_<std::allocator<void> > LoadGraphResponse;

typedef boost::shared_ptr< ::graph_msgs::LoadGraphResponse > LoadGraphResponsePtr;
typedef boost::shared_ptr< ::graph_msgs::LoadGraphResponse const> LoadGraphResponseConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::graph_msgs::LoadGraphResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::graph_msgs::LoadGraphResponse_<ContainerAllocator1> & lhs, const ::graph_msgs::LoadGraphResponse_<ContainerAllocator2> & rhs)
{
  return lhs.graph == rhs.graph &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::graph_msgs::LoadGraphResponse_<ContainerAllocator1> & lhs, const ::graph_msgs::LoadGraphResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace graph_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6a7dcd77b4b6152936793b80dfac506";
  }

  static const char* value(const ::graph_msgs::LoadGraphResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6a7dcd77b4b6152ULL;
  static const uint64_t static_value2 = 0x936793b80dfac506ULL;
};

template<class ContainerAllocator>
struct DataType< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "graph_msgs/LoadGraphResponse";
  }

  static const char* value(const ::graph_msgs::LoadGraphResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Result code defintions\n"
"uint8 RESULT_SUCCESS=0\n"
"uint8 RESULT_GRAPH_DOES_NOT_EXIST=1\n"
"uint8 RESULT_INVALID_GRAPH_FILE_PATH=2\n"
"uint8 RESULT_UNDEFINED_FAILURE=255\n"
"\n"
"# Returned graph is only valid if result equals RESULT_SUCCESS\n"
"graph_msgs/Graph graph\n"
"uint8 result\n"
"\n"
"================================================================================\n"
"MSG: graph_msgs/Graph\n"
"std_msgs/Header header\n"
"GraphMetaData meta_data\n"
"Vertex[] vertices       # List of vertices\n"
"Edge[] edges            # List of edges\n"
"Property[] properties \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: graph_msgs/GraphMetaData\n"
"uint8 DIRECTED=0\n"
"uint8 UNDIRECTED=1\n"
"\n"
"std_msgs/Header header\n"
"string graph_name\n"
"uint8 graph_type\n"
"uint32 number_of_vertices\n"
"uint32 number_of_edges\n"
"================================================================================\n"
"MSG: graph_msgs/Vertex\n"
"# Vertex types\n"
"uint8 NORMAL=0\n"
"uint8 PARK=1\n"
"uint8 CHARGE=2\n"
"uint8 CONTROL=3\n"
"uint8 REPORT=4\n"
"\n"
"uint32 id\n"
"string name\n"
"string alias\n"
"uint8 type\n"
"bool ignore_orientation\n"
"geometry_msgs/Pose pose\n"
"Property[] properties\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: graph_msgs/Property\n"
"string key\n"
"string value\n"
"================================================================================\n"
"MSG: graph_msgs/Edge\n"
"# Edge types\n"
"uint8 STRAIGHT_LINE=0\n"
"uint8 CUBIC_BEZIER=1\n"
"\n"
"# Edge direction types\n"
"uint8 FORWARD=0\n"
"uint8 REVERSE=1\n"
"uint8 BIDIRECTIONAL=2\n"
"\n"
"# Creation types \n"
"uint8 CREATED=0     # The edge is created\n"
"uint8 GENERATED=1   # The edge is generated\n"
"\n"
"string name\n"
"string alias\n"
"uint8 type\n"
"uint8 edge_direction_type\n"
"uint8 creation_type         #FIXME: This creation type is not required. The graph data structure should be able to handle both\n"
"uint32 source_vertex_id\n"
"uint32 target_vertex_id\n"
"float64 length\n"
"float64 cost_factor         # A factor by which the traversal cost is multiplied. In this case the length of the edge\n"
"bool bidirectional\n"
"bool independent_orientation\n"
"geometry_msgs/Pose[] control_points\n"
"geometry_msgs/Pose control_orientation\n"
"geometry_msgs/PoseArray poses   # Can contain the poses for the curve\n"
"Property[] properties\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseArray\n"
"# An array of poses with a header for global reference.\n"
"\n"
"Header header\n"
"\n"
"Pose[] poses\n"
;
  }

  static const char* value(const ::graph_msgs::LoadGraphResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.graph);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadGraphResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::graph_msgs::LoadGraphResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::graph_msgs::LoadGraphResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "graph: ";
    Printer< ::graph_msgs::Graph_<ContainerAllocator> >::stream(s, indent + "  ", v.graph);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRAPH_MSGS_MESSAGE_LOADGRAPHRESPONSE_H
