// Generated by gencpp from file graph_msgs/LoadGraph.msg
// DO NOT EDIT!


#ifndef GRAPH_MSGS_MESSAGE_LOADGRAPH_H
#define GRAPH_MSGS_MESSAGE_LOADGRAPH_H

#include <ros/service_traits.h>


#include <graph_msgs/LoadGraphRequest.h>
#include <graph_msgs/LoadGraphResponse.h>


namespace graph_msgs
{

struct LoadGraph
{

typedef LoadGraphRequest Request;
typedef LoadGraphResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadGraph
} // namespace graph_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graph_msgs::LoadGraph > {
  static const char* value()
  {
    return "3a21dc3edb22fc7f6da0621dca59dd0f";
  }

  static const char* value(const ::graph_msgs::LoadGraph&) { return value(); }
};

template<>
struct DataType< ::graph_msgs::LoadGraph > {
  static const char* value()
  {
    return "graph_msgs/LoadGraph";
  }

  static const char* value(const ::graph_msgs::LoadGraph&) { return value(); }
};


// service_traits::MD5Sum< ::graph_msgs::LoadGraphRequest> should match
// service_traits::MD5Sum< ::graph_msgs::LoadGraph >
template<>
struct MD5Sum< ::graph_msgs::LoadGraphRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graph_msgs::LoadGraph >::value();
  }
  static const char* value(const ::graph_msgs::LoadGraphRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_msgs::LoadGraphRequest> should match
// service_traits::DataType< ::graph_msgs::LoadGraph >
template<>
struct DataType< ::graph_msgs::LoadGraphRequest>
{
  static const char* value()
  {
    return DataType< ::graph_msgs::LoadGraph >::value();
  }
  static const char* value(const ::graph_msgs::LoadGraphRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graph_msgs::LoadGraphResponse> should match
// service_traits::MD5Sum< ::graph_msgs::LoadGraph >
template<>
struct MD5Sum< ::graph_msgs::LoadGraphResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graph_msgs::LoadGraph >::value();
  }
  static const char* value(const ::graph_msgs::LoadGraphResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_msgs::LoadGraphResponse> should match
// service_traits::DataType< ::graph_msgs::LoadGraph >
template<>
struct DataType< ::graph_msgs::LoadGraphResponse>
{
  static const char* value()
  {
    return DataType< ::graph_msgs::LoadGraph >::value();
  }
  static const char* value(const ::graph_msgs::LoadGraphResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRAPH_MSGS_MESSAGE_LOADGRAPH_H
