// Generated by gencpp from file graph_msgs/SaveGraph.msg
// DO NOT EDIT!


#ifndef GRAPH_MSGS_MESSAGE_SAVEGRAPH_H
#define GRAPH_MSGS_MESSAGE_SAVEGRAPH_H

#include <ros/service_traits.h>


#include <graph_msgs/SaveGraphRequest.h>
#include <graph_msgs/SaveGraphResponse.h>


namespace graph_msgs
{

struct SaveGraph
{

typedef SaveGraphRequest Request;
typedef SaveGraphResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveGraph
} // namespace graph_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graph_msgs::SaveGraph > {
  static const char* value()
  {
    return "70cd2cf58e0678fd28ff2029ea82cfd1";
  }

  static const char* value(const ::graph_msgs::SaveGraph&) { return value(); }
};

template<>
struct DataType< ::graph_msgs::SaveGraph > {
  static const char* value()
  {
    return "graph_msgs/SaveGraph";
  }

  static const char* value(const ::graph_msgs::SaveGraph&) { return value(); }
};


// service_traits::MD5Sum< ::graph_msgs::SaveGraphRequest> should match
// service_traits::MD5Sum< ::graph_msgs::SaveGraph >
template<>
struct MD5Sum< ::graph_msgs::SaveGraphRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graph_msgs::SaveGraph >::value();
  }
  static const char* value(const ::graph_msgs::SaveGraphRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_msgs::SaveGraphRequest> should match
// service_traits::DataType< ::graph_msgs::SaveGraph >
template<>
struct DataType< ::graph_msgs::SaveGraphRequest>
{
  static const char* value()
  {
    return DataType< ::graph_msgs::SaveGraph >::value();
  }
  static const char* value(const ::graph_msgs::SaveGraphRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graph_msgs::SaveGraphResponse> should match
// service_traits::MD5Sum< ::graph_msgs::SaveGraph >
template<>
struct MD5Sum< ::graph_msgs::SaveGraphResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graph_msgs::SaveGraph >::value();
  }
  static const char* value(const ::graph_msgs::SaveGraphResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graph_msgs::SaveGraphResponse> should match
// service_traits::DataType< ::graph_msgs::SaveGraph >
template<>
struct DataType< ::graph_msgs::SaveGraphResponse>
{
  static const char* value()
  {
    return DataType< ::graph_msgs::SaveGraph >::value();
  }
  static const char* value(const ::graph_msgs::SaveGraphResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRAPH_MSGS_MESSAGE_SAVEGRAPH_H
