# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lift_action/LiftAction.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LiftAction(genpy.Message):
  _md5sum = "74abac7a70a7dbf2314bec741f0342c4"
  _type = "lift_action/LiftAction"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string unique_id
bool reached
int16 rack
int16 shelf
int16 acr_shelf
int16 action
string whole_bin_no
string putaway_barcode"""
  __slots__ = ['unique_id','reached','rack','shelf','acr_shelf','action','whole_bin_no','putaway_barcode']
  _slot_types = ['string','bool','int16','int16','int16','int16','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       unique_id,reached,rack,shelf,acr_shelf,action,whole_bin_no,putaway_barcode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LiftAction, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.unique_id is None:
        self.unique_id = ''
      if self.reached is None:
        self.reached = False
      if self.rack is None:
        self.rack = 0
      if self.shelf is None:
        self.shelf = 0
      if self.acr_shelf is None:
        self.acr_shelf = 0
      if self.action is None:
        self.action = 0
      if self.whole_bin_no is None:
        self.whole_bin_no = ''
      if self.putaway_barcode is None:
        self.putaway_barcode = ''
    else:
      self.unique_id = ''
      self.reached = False
      self.rack = 0
      self.shelf = 0
      self.acr_shelf = 0
      self.action = 0
      self.whole_bin_no = ''
      self.putaway_barcode = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.unique_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B4h().pack(_x.reached, _x.rack, _x.shelf, _x.acr_shelf, _x.action))
      _x = self.whole_bin_no
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.putaway_barcode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.unique_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.unique_id = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.reached, _x.rack, _x.shelf, _x.acr_shelf, _x.action,) = _get_struct_B4h().unpack(str[start:end])
      self.reached = bool(self.reached)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.whole_bin_no = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.whole_bin_no = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.putaway_barcode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.putaway_barcode = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.unique_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B4h().pack(_x.reached, _x.rack, _x.shelf, _x.acr_shelf, _x.action))
      _x = self.whole_bin_no
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.putaway_barcode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.unique_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.unique_id = str[start:end]
      _x = self
      start = end
      end += 9
      (_x.reached, _x.rack, _x.shelf, _x.acr_shelf, _x.action,) = _get_struct_B4h().unpack(str[start:end])
      self.reached = bool(self.reached)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.whole_bin_no = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.whole_bin_no = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.putaway_barcode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.putaway_barcode = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B4h = None
def _get_struct_B4h():
    global _struct_B4h
    if _struct_B4h is None:
        _struct_B4h = struct.Struct("<B4h")
    return _struct_B4h
