# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lift_action/LiftFeedback.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LiftFeedback(genpy.Message):
  _md5sum = "6588a9452ee8a183f42490d3b437bdbe"
  _type = "lift_action/LiftFeedback"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string unique_id
int16 acr_shelf
int16 action
bool status
bool failStatus"""
  __slots__ = ['unique_id','acr_shelf','action','status','failStatus']
  _slot_types = ['string','int16','int16','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       unique_id,acr_shelf,action,status,failStatus

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LiftFeedback, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.unique_id is None:
        self.unique_id = ''
      if self.acr_shelf is None:
        self.acr_shelf = 0
      if self.action is None:
        self.action = 0
      if self.status is None:
        self.status = False
      if self.failStatus is None:
        self.failStatus = False
    else:
      self.unique_id = ''
      self.acr_shelf = 0
      self.action = 0
      self.status = False
      self.failStatus = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.unique_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2h2B().pack(_x.acr_shelf, _x.action, _x.status, _x.failStatus))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.unique_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.unique_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.acr_shelf, _x.action, _x.status, _x.failStatus,) = _get_struct_2h2B().unpack(str[start:end])
      self.status = bool(self.status)
      self.failStatus = bool(self.failStatus)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.unique_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2h2B().pack(_x.acr_shelf, _x.action, _x.status, _x.failStatus))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.unique_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.unique_id = str[start:end]
      _x = self
      start = end
      end += 6
      (_x.acr_shelf, _x.action, _x.status, _x.failStatus,) = _get_struct_2h2B().unpack(str[start:end])
      self.status = bool(self.status)
      self.failStatus = bool(self.failStatus)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h2B = None
def _get_struct_2h2B():
    global _struct_2h2B
    if _struct_2h2B is None:
        _struct_2h2B = struct.Struct("<2h2B")
    return _struct_2h2B
